EX4: command_line_parsing.c File Reference
client/command_line_parsing.c File Reference
Implementation of all command line parsing functions.
#include "command_line_parsing.h"
Functions
error_e parse_command_line_input (int argc_, char *argv_[], client_command_line_parms_t *p_output_args)
parsing the command line, validates input integrity and fills the arg structure.
static void print_usage_msg (void)
print the command line usage for Factori program.
Detailed Description
Implementation of all command line parsing functions.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file client/command_line_parsing.c.
Function Documentation
parse_command_line_input()
error_e parse_command_line_input (int argc_, char * argv_[], client_command_line_parms_t * p_output_args)
parsing the command line, validates input integrity and fills the arg structure.
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
Definition at line 33 of file client/command_line_parsing.c.
 {
     // Debug Prefix /////////////
     SET_CONSOLE_COLOR(MAGENTA__CONSOLE_COLOR_CODE);
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Input Arguments: <ip_address>, <port_number>, <username>\n");
     for (int u_param_idx = 0; u_param_idx < argc_; u_param_idx++)
     {
         DEBUG_PRINT_ARG("%s\n", argv_[u_param_idx]);
     }
     error_e e_status = ERROR_OK;
     // Verify number of arguments.
     if ((argc_ < MIN_ALLOWED_ARGS) || (argc_ > MAX_ALLOWED_ARGS))
     {
         print_error_msg("Invalid number of arguments, given %d while expecting between %d to %d (inclusive)\n", argc_, MIN_ALLOWED_ARGS, MAX_ALLOWED_ARGS);
         e_status = ERROR_INVALID_NUMBER_OF_PARAMETERS_E;
     }
     else
     {
         /* Valid argc_ input */
         e_status = get_port_num_and_string(&p_output_args->port_num, p_output_args->port_string, argv_[PORT_NUMBER_ARG_INDEX]);
         /* TODO: Need to validate correctness of IP sddress and username before! copying it.*/
         strcpy_s(p_output_args->ip_string, IP_MAX_LEGNTH_STRING, argv_[IP_ADDRESS_ARG_INDEX]);
         strcpy_s(p_output_args->username_string, USERNAME_MAX_LEGNTH_STRING, argv_[USERNAME_ARG_INDEX]);
     }
     // Print useage instructions
     if(ERROR_OK != e_status)
     {
         print_usage_msg();
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     SET_CONSOLE_WHITE();
     return e_status;
 }
References DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_PARAMETERS_E, ERROR_OK, get_port_num_and_string(), IP_ADDRESS_ARG_INDEX, IP_MAX_LEGNTH_STRING, client_command_line_parms_s::ip_string, MAGENTA__CONSOLE_COLOR_CODE, MAX_ALLOWED_ARGS, MIN_ALLOWED_ARGS, client_command_line_parms_s::port_num, PORT_NUMBER_ARG_INDEX, client_command_line_parms_s::port_string, print_error_msg, print_usage_msg(), SET_CONSOLE_COLOR, SET_CONSOLE_WHITE, USERNAME_ARG_INDEX, USERNAME_MAX_LEGNTH_STRING, and client_command_line_parms_s::username_string.
print_usage_msg()
static void print_usage_msg (void) static
print the command line usage for Factori program.
Definition at line 86 of file client/command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     printf("Usage:\n");
     printf("Client.exe ip_address port_number username\n");
     printf("\n");
     printf("Arguments:\n");
     printf("    ip_address       : The server is going to use the local ip address (127.0.0.1),\n");
     printf("                       you can enter another address but things won't work...\n");
     printf("    port_number      : What port to listen to must be between 1000 to 65000.\n");
     printf("    username         : Username must not include spaces, and upto 20 characters.\n");
     printf("\n");
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
 }
References DEBUG_PRINT_FUNCTION_END, and DEBUG_PRINT_FUNCTION_START.
Referenced by parse_command_line_input().