EX4: common_command_line_parsing.c File Reference
common_command_line_parsing.c File Reference
#include "common_command_line_parsing.h"
Functions
int get_int_from_string (const char *p_string)
Get the int from string object extract digits character from string.
error_e get_port_num_and_string (int *p_output_port_num, char *output_port_string, char *input_string)
Function Documentation
get_int_from_string()
int get_int_from_string (const char * p_string)
Get the int from string object extract digits character from string.
Parameters
[in] p_string
Returns
int return 0 will be invalid return value, thought the input string can potentionaly be 0. This value should be treated carefully by caller function.
Definition at line 37 of file common_command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT_ARG("p_string = %s\n", p_string);
     // atoi will return an integer withing the string, 0 if it is not only a string, but 99Hello will return 99.
     int integer_within_string = atoi(p_string);
     // Verify the string only contains digits.
     // Since this string was given by command line, it is safe to assume it is valid, and has string termination.
     uint32_t u_string_idx = 0;
     while(p_string[u_string_idx] != '\0')
     {
         if(isdigit(p_string[u_string_idx]) == 0)
         {
             print_error_msg("The string provided: %s,\n Is invalid since it does not contain digits only!", p_string);
             integer_within_string = 0L;
             break;
         }
         u_string_idx++;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return integer_within_string;
 }
References DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, and print_error_msg.
Referenced by get_port_num_and_string().
get_port_num_and_string()
error_e get_port_num_and_string (int * p_output_port_num, char * output_port_string, char * input_string)
Definition at line 69 of file common_command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     int port_number_of_digits = strlen(input_string);
     if(MAX_NUMBER_OF_PORT_DIGITS < port_number_of_digits)
     {
         print_error_msg("The port number has invalid number of digits. Assumed max number is %d while received %d\n", MAX_NUMBER_OF_PORT_DIGITS, port_number_of_digits);
         e_status = ERROR_INVALID_PORT_NUMBER_E;
     }
     // copy port string
     errno_t strcpy_status = strcpy_s(output_port_string, MAX_NUMBER_OF_PORT_DIGITS + 1, input_string);
     if(strcpy_status)
     {
         print_error_msg("Failed to copy string of task file\n")
         e_status = ERROR_STRCPY_FAILED_E;
     }
     // Convert string to int
     *p_output_port_num = get_int_from_string(output_port_string);
     // Check number validity
     if(INVALID_INTEGER_VALUE == *p_output_port_num)
     {
         print_error_msg("parse_command_line_input(): Failed to parse port number.\n");
         e_status = ERROR_INVALID_PORT_NUMBER_E;
     }
     // Check number valid range
     if(*p_output_port_num < MIN_PORT_NUM || *p_output_port_num > MAX_PORT_NUM)
     {
         print_error_msg("Port number is out of legal range which is [%d, %d].\n", MIN_PORT_NUM, MAX_PORT_NUM);
         e_status = ERROR_INVALID_PORT_NUMBER_E;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_PORT_NUMBER_E, ERROR_OK, ERROR_STRCPY_FAILED_E, get_int_from_string(), INVALID_INTEGER_VALUE, MAX_NUMBER_OF_PORT_DIGITS, MAX_PORT_NUM, MIN_PORT_NUM, and print_error_msg.
Referenced by parse_command_line_input().