EX4: command_line_parsing.c File Reference
command_line_parsing.c File Reference
Implementation of all command line parsing functions.
#include "command_line_parsing.h"
Functions
error_e parse_command_line_input (int argc_, char *argv_[], factori_args_t *p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
static DWORD parse_num_of_threads (const char *p_num_of_threads_string)
converts string to int. Validates string has only numbers.
static DWORD parse_num_of_tasks (const char *p_num_of_tasks_string)
converts string to int. Validates string has only numbers.
static DWORD get_int_from_string (const char *p_string)
Get the int from string object extract digits character from string.
static void print_usage_msg (void)
print the command line usage for Factori program.
Detailed Description
Implementation of all command line parsing functions.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file command_line_parsing.c.
Function Documentation
get_int_from_string()
static DWORD get_int_from_string (const char * p_string) static
Get the int from string object extract digits character from string.
Parameters
[in] p_string
Returns
int return 0 will be invalid return value, thought the input string can potentionaly be 0. This value should be treated carefully by caller function.
Definition at line 188 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT_ARG("p_string = %s\n", p_string);
     // atoi will return an integer withing the string, 0 if it is not only a string, but 99Hello will return 99.
     DWORD integer_within_string = atoi(p_string);
     // Verify the string only contains digits.
     // Since this string was given by command line, it is safe to assume it is valid, and has string termination.
     uint32_t u_string_idx = 0;
     while(p_string[u_string_idx] != '\0')
     {
         if(isdigit(p_string[u_string_idx]) == 0)
         {
             print_error_msg("The string provided: %s,\n Is invalid since it does not contain digits only!", p_string);
             integer_within_string = 0L;
             break;
         }
         u_string_idx++;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return integer_within_string;
 }
References DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, and print_error_msg.
Referenced by parse_num_of_tasks(), and parse_num_of_threads().
parse_command_line_input()
error_e parse_command_line_input (int argc_, char * argv_[], factori_args_t * p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
[MUST]input file name string: holdes the full/relative path for the text file to be cyphered. MUST
[MUST]encryption key: the key the program will use to encrypt or decrypt the file.
[MUST]number of threads: the number of threads to use to encrypt or decrypt the file. Default: 1 Implemntation: Stright forward, reading the input, and constantly checking for the validity fo the input. Pitfalls: converting the string to int, allocating memory for strings.
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
Definition at line 41 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Input Arguments: <program_name>, <task_input_file_name>, <priority_input_file_name>, <num_of_threads>,\n");
     for (int u_param_idx = 0; u_param_idx < argc_; u_param_idx++)
     {
         DEBUG_PRINT_ARG("%s\n", argv_[u_param_idx]);
     }
     error_e e_status = ERROR_OK;
     // Verify number of arguments.
     if ((argc_ < MIN_ALLOWED_ARGS) || (argc_ > MAX_ALLOWED_ARGS))
     {
         print_error_msg("Invalid number of arguments, given %d while expecting between %d to %d (inclusive)\n", argc_, MIN_ALLOWED_ARGS, MAX_ALLOWED_ARGS);
         e_status = ERROR_INVALID_NUMBER_OF_PARAMETERS_E;
     }
     else
     {
         /* Valid argc_ input */
         //validate length of path
         DWORD task_file_path_len = strlen(argv_[TASK_FILE_NAME_ARG_INDEX]);
         if(MAX_PATH < task_file_path_len)
         {
             print_error_msg("The length of task file path is greater then the maximum which is %d\n", MAX_PATH);
             e_status = ERROR_INVALID_TASK_FILE_PATH_LENGTH_E;
         }
         DWORD priority_file_path_len = strlen(argv_[PRIORITY_FILE_NAME_ARG_INDEX]);
         // copy task file named
         errno_t strcpy_status = strcpy_s(p_output_args->a_task_file_name, MAX_PATH, argv_[TASK_FILE_NAME_ARG_INDEX]);
         if(strcpy_status)
         {
             print_error_msg("Failed to copy string of task file\n")
             e_status = ERROR_STRCPY_FAILED_E;
         }
         p_output_args->p_priority_file_name       = argv_[PRIORITY_FILE_NAME_ARG_INDEX];
         p_output_args->num_of_threads             = parse_num_of_threads(argv_[THREAD_NUM_ARG_INDEX]);
         p_output_args->num_of_tasks               = parse_num_of_tasks(argv_[TASKS_NUM_ARG_INDEX]);
     }
     if(INVALID_INTEGER_VALUE == p_output_args->num_of_threads)
     {
         print_error_msg("parse_command_line_input(): Failed to parse number of threads.\n");
         e_status = ERROR_INVALID_THREAD_NUM_E;
     }
     if(INVALID_INTEGER_VALUE == p_output_args->num_of_tasks)
     {
         print_error_msg("parse_command_line_input(): Failed to parse number of tasks.\n");
         e_status = ERROR_INVALID_THREAD_NUM_E;
     }
     // Print useage instructions
     if(ERROR_OK != e_status)
     {
         print_usage_msg();
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References factori_args_s::a_task_file_name, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_PARAMETERS_E, ERROR_INVALID_TASK_FILE_PATH_LENGTH_E, ERROR_INVALID_THREAD_NUM_E, ERROR_OK, ERROR_STRCPY_FAILED_E, INVALID_INTEGER_VALUE, MAX_ALLOWED_ARGS, MIN_ALLOWED_ARGS, factori_args_s::num_of_tasks, factori_args_s::num_of_threads, factori_args_s::p_priority_file_name, parse_num_of_tasks(), parse_num_of_threads(), print_error_msg, print_usage_msg(), PRIORITY_FILE_NAME_ARG_INDEX, TASK_FILE_NAME_ARG_INDEX, TASKS_NUM_ARG_INDEX, and THREAD_NUM_ARG_INDEX.
parse_num_of_tasks()
static DWORD parse_num_of_tasks (const char * p_num_of_tasks_string) static
converts string to int. Validates string has only numbers.
Parameters
[in] p_num_of_tasks_string
Returns
int success: number of threads, fail: -1
Definition at line 153 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT_ARG("p_num_of_tasks_string = %s\n", p_num_of_tasks_string);
     int num_of_tasks = INVALID_INTEGER_VALUE;     // Initialized to failed value. Will be changed to valid on success.
     if(NULL == p_num_of_tasks_string)
     {
         print_error_msg("parse_num_of_tasks(): Received a NULL pointer\n");
     }
     // Extract number from string.
     num_of_tasks = get_int_from_string(p_num_of_tasks_string);
     if(num_of_tasks < 0 )
     {
         print_error_msg("parse_num_of_tasks(): Invalid number of tasks string.\nRecieved string: %s\nExtracted number: %d\n", p_num_of_tasks_string, num_of_tasks);
         num_of_tasks = INVALID_INTEGER_VALUE;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return num_of_tasks;
 }
References DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, get_int_from_string(), INVALID_INTEGER_VALUE, and print_error_msg.
Referenced by parse_command_line_input().
parse_num_of_threads()
static DWORD parse_num_of_threads (const char * p_num_of_threads_string) static
converts string to int. Validates string has only numbers.
Parameters
[in] p_num_of_threads_string
Returns
int success: number of threads, fail: -1.
Definition at line 119 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT_ARG("p_num_of_threads_string = %s\n", p_num_of_threads_string);
     int num_of_threads = INVALID_INTEGER_VALUE;     // Initialized to failed value. Will be changed to valid on success.
     if(NULL == p_num_of_threads_string)
     {
         print_error_msg("parse_num_of_threads(): Received a NULL pointer");
     }
     // Extract number from string.
     num_of_threads = get_int_from_string(p_num_of_threads_string);
     if(num_of_threads < DEFUALT_THREAD_NUM || num_of_threads > MAX_THREAD_NUM)
     {
         print_error_msg("parse_num_of_threads(): Invalid number of threads string.\nRecieved string: %s\nExtracted number: %d\n", p_num_of_threads_string, num_of_threads);
         num_of_threads = INVALID_INTEGER_VALUE;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return num_of_threads;
 }
References DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, get_int_from_string(), INVALID_INTEGER_VALUE, MAX_THREAD_NUM, and print_error_msg.
Referenced by parse_command_line_input().
print_usage_msg()
static void print_usage_msg (void) static
print the command line usage for Factori program.
Definition at line 224 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     printf("Usage:\n");
     printf("Factori.exe task_input_file_name priority_input_file_name num_of_threads\n");
     printf("\n");
     printf("Arguments:\n");
     printf("    task_input_file_name      : The file containing the list of numbers which we want to compute the prime factors for.\n");
     printf("                              : File name, or relative path, or full path.\n");
     printf("    priority_input_file_name  : The file containing the list of numbers which we want to compute the prime factors for.\n");
     printf("                              : File name, or relative path, or full path.\n");
     printf("    num_of_threads            : The number of threads to be used by the program.\n");
     printf("                              : An integer between %d to %d (inclusive).\n", DEFUALT_THREAD_NUM, MAX_THREAD_NUM);
     printf("\n");
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, DEFUALT_THREAD_NUM, and MAX_THREAD_NUM.
Referenced by parse_command_line_input().