EX4: command_line_parsing_ext.h File Reference
command_line_parsing_ext.h File Reference
Decleration and defenitions of all command line parsing related function and macros.
#include <Windows.h>
#include "common_types.h"
Data Structures
struct factori_args_s
All the command line argmuents after parsing them. task file name - hard copy information from argv[0] to remove dependency of shared memory. This string is going to be read by multiple threads. priority file name number of threads number of tasks: should match te number of lines in the tasks and priority files.
Typedefs
typedef struct factori_args_s factori_args_t
All the command line argmuents after parsing them. task file name - hard copy information from argv[0] to remove dependency of shared memory. This string is going to be read by multiple threads. priority file name number of threads number of tasks: should match te number of lines in the tasks and priority files.
Functions
error_e parse_command_line_input (int argc_, char *argv_[], factori_args_t *p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
Detailed Description
Decleration and defenitions of all command line parsing related function and macros.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file command_line_parsing_ext.h.
Typedef Documentation
factori_args_t
typedef struct factori_args_s factori_args_t
All the command line argmuents after parsing them. task file name - hard copy information from argv[0] to remove dependency of shared memory. This string is going to be read by multiple threads. priority file name number of threads number of tasks: should match te number of lines in the tasks and priority files.
Function Documentation
parse_command_line_input()
error_e parse_command_line_input (int argc_, char * argv_[], factori_args_t * p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
[MUST]tasks_file :the full/relative path for the text file to be cyphered. MUST
[MUST]priorities_file :the key the program will use to encrypt or decrypt the file.
[MUST]num_of_tasks :indication weather to encrypt or decrypt the file, the option are '-e' and '-d'. Defualt: encrypt.
[MUST]number_of_threads :the number of threads to use to encrypt or decrypt the file. Default: 1
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
[MUST]input file name string: holdes the full/relative path for the text file to be cyphered. MUST
[MUST]encryption key: the key the program will use to encrypt or decrypt the file.
[MUST]number of threads: the number of threads to use to encrypt or decrypt the file. Default: 1 Implemntation: Stright forward, reading the input, and constantly checking for the validity fo the input. Pitfalls: converting the string to int, allocating memory for strings.
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
Definition at line 41 of file command_line_parsing.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Input Arguments: <program_name>, <task_input_file_name>, <priority_input_file_name>, <num_of_threads>,\n");
     for (int u_param_idx = 0; u_param_idx < argc_; u_param_idx++)
     {
         DEBUG_PRINT_ARG("%s\n", argv_[u_param_idx]);
     }
     error_e e_status = ERROR_OK;
     // Verify number of arguments.
     if ((argc_ < MIN_ALLOWED_ARGS) || (argc_ > MAX_ALLOWED_ARGS))
     {
         print_error_msg("Invalid number of arguments, given %d while expecting between %d to %d (inclusive)\n", argc_, MIN_ALLOWED_ARGS, MAX_ALLOWED_ARGS);
         e_status = ERROR_INVALID_NUMBER_OF_PARAMETERS_E;
     }
     else
     {
         /* Valid argc_ input */
         //validate length of path
         DWORD task_file_path_len = strlen(argv_[TASK_FILE_NAME_ARG_INDEX]);
         if(MAX_PATH < task_file_path_len)
         {
             print_error_msg("The length of task file path is greater then the maximum which is %d\n", MAX_PATH);
             e_status = ERROR_INVALID_TASK_FILE_PATH_LENGTH_E;
         }
         DWORD priority_file_path_len = strlen(argv_[PRIORITY_FILE_NAME_ARG_INDEX]);
         // copy task file named
         errno_t strcpy_status = strcpy_s(p_output_args->a_task_file_name, MAX_PATH, argv_[TASK_FILE_NAME_ARG_INDEX]);
         if(strcpy_status)
         {
             print_error_msg("Failed to copy string of task file\n")
             e_status = ERROR_STRCPY_FAILED_E;
         }
         p_output_args->p_priority_file_name       = argv_[PRIORITY_FILE_NAME_ARG_INDEX];
         p_output_args->num_of_threads             = parse_num_of_threads(argv_[THREAD_NUM_ARG_INDEX]);
         p_output_args->num_of_tasks               = parse_num_of_tasks(argv_[TASKS_NUM_ARG_INDEX]);
     }
     if(INVALID_INTEGER_VALUE == p_output_args->num_of_threads)
     {
         print_error_msg("parse_command_line_input(): Failed to parse number of threads.\n");
         e_status = ERROR_INVALID_THREAD_NUM_E;
     }
     if(INVALID_INTEGER_VALUE == p_output_args->num_of_tasks)
     {
         print_error_msg("parse_command_line_input(): Failed to parse number of tasks.\n");
         e_status = ERROR_INVALID_THREAD_NUM_E;
     }
     // Print useage instructions
     if(ERROR_OK != e_status)
     {
         print_usage_msg();
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References factori_args_s::a_task_file_name, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_PARAMETERS_E, ERROR_INVALID_TASK_FILE_PATH_LENGTH_E, ERROR_INVALID_THREAD_NUM_E, ERROR_OK, ERROR_STRCPY_FAILED_E, INVALID_INTEGER_VALUE, MAX_ALLOWED_ARGS, MIN_ALLOWED_ARGS, factori_args_s::num_of_tasks, factori_args_s::num_of_threads, factori_args_s::p_priority_file_name, parse_num_of_tasks(), parse_num_of_threads(), print_error_msg, print_usage_msg(), PRIORITY_FILE_NAME_ARG_INDEX, TASK_FILE_NAME_ARG_INDEX, TASKS_NUM_ARG_INDEX, and THREAD_NUM_ARG_INDEX.