var files_dup =
[
    [ "client.c", "client_8c.html", "client_8c" ],
    [ "client.h", "client_8h.html", "client_8h" ],
    [ "server/command_line_parsing.c", "server_2command__line__parsing_8c.html", "server_2command__line__parsing_8c" ],
    [ "client/command_line_parsing.c", "client_2command__line__parsing_8c.html", "client_2command__line__parsing_8c" ],
    [ "server/command_line_parsing.h", "server_2command__line__parsing_8h.html", "server_2command__line__parsing_8h" ],
    [ "client/command_line_parsing.h", "client_2command__line__parsing_8h.html", "client_2command__line__parsing_8h" ],
    [ "common_command_line_parsing.c", "common__command__line__parsing_8c.html", "common__command__line__parsing_8c" ],
    [ "common_command_line_parsing.h", "common__command__line__parsing_8h.html", "common__command__line__parsing_8h" ],
    [ "common_command_line_parsing_ext.h", "common__command__line__parsing__ext_8h.html", "common__command__line__parsing__ext_8h" ],
    [ "common_types.h", "common__types_8h.html", "common__types_8h" ],
    [ "count_cows_bulls.c", "count__cows__bulls_8c.html", "count__cows__bulls_8c" ],
    [ "count_cows_bulls.h", "count__cows__bulls_8h.html", "count__cows__bulls_8h" ],
    [ "file_utils.c", "file__utils_8c.html", "file__utils_8c" ],
    [ "file_utils.h", "file__utils_8h.html", "file__utils_8h" ],
    [ "file_utils_ext.h", "file__utils__ext_8h.html", "file__utils__ext_8h" ],
    [ "inter_thread_communication.c", "inter__thread__communication_8c.html", "inter__thread__communication_8c" ],
    [ "inter_thread_communication.h", "inter__thread__communication_8h.html", "inter__thread__communication_8h" ],
    [ "lock.c", "lock_8c.html", "lock_8c" ],
    [ "lock.h", "lock_8h.html", "lock_8h" ],
    [ "lock_ext.h", "lock__ext_8h.html", "lock__ext_8h" ],
    [ "read_write_msg.c", "read__write__msg_8c.html", "read__write__msg_8c" ],
    [ "read_write_msg.h", "read__write__msg_8h.html", null ],
    [ "read_write_msg_ext.h", "read__write__msg__ext_8h.html", "read__write__msg__ext_8h" ],
    [ "send_recv_messages_ext.h", "send__recv__messages__ext_8h.html", "send__recv__messages__ext_8h" ],
    [ "server.c", "server_8c.html", "server_8c" ],
    [ "server.h", "server_8h.html", "server_8h" ],
    [ "socket_send_recv_tools.c", "socket__send__recv__tools_8c.html", "socket__send__recv__tools_8c" ],
    [ "socket_send_recv_tools.h", "socket__send__recv__tools_8h.html", "socket__send__recv__tools_8h" ],
    [ "trace.c", "trace_8c.html", null ],
    [ "trace.h", "trace_8h.html", "trace_8h" ]
];