EX4: inter_thread_communication.h File Reference
inter_thread_communication.h File Reference
Decleration and defenitions of all command line parsing related function and macros.
#include <stdio.h>
#include "common_types.h"
#include "trace.h"
#include "lock_ext.h"
Macros
#define INTER_THREAD_COMMUNICATION_FILE_NAME_STRING ("GameSession.txt")
#define MAXIMUM_READ_BUFFER_SIZE_IN_BYTES (128)
Typedefs
typedef enum player_position_e player_position_e
Decide on the access order to the communication file.
Enumerations
enum player_position_e { FIRST_PLAYER_E = 0, SECOND_PLAYER_E = 1, MAX_PLAYERS = 2, INVALID_PLAYER_E }
Decide on the access order to the communication file.
Functions
int is_file_exists (lock_t *p_read_lock)
error_e create_comm_file (lock_t *p_lock)
Create a comm file object.
player_position_e first_or_second_to_play (lock_t *p_lock, const int file_position)
error_e send_message_using_file (lock_t *p_lock, const char *const p_msg_to_send, const int msg_size_in_bytes, int *p_file_position)
error_e read_message_using_file (lock_t *p_lock, char *p_recv_msg, int *msg_size_in_bytes, int *p_file_position)
Detailed Description
Decleration and defenitions of all command line parsing related function and macros.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file inter_thread_communication.h.
Macro Definition Documentation
INTER_THREAD_COMMUNICATION_FILE_NAME_STRING
#define INTER_THREAD_COMMUNICATION_FILE_NAME_STRING ("GameSession.txt")
Definition at line 29 of file inter_thread_communication.h.
MAXIMUM_READ_BUFFER_SIZE_IN_BYTES
#define MAXIMUM_READ_BUFFER_SIZE_IN_BYTES (128)
Definition at line 30 of file inter_thread_communication.h.
Typedef Documentation
player_position_e
typedef enum player_position_e player_position_e
Decide on the access order to the communication file.
Enumeration Type Documentation
player_position_e
enum player_position_e
Decide on the access order to the communication file.
Enumerator
FIRST_PLAYER_E
SECOND_PLAYER_E
MAX_PLAYERS
INVALID_PLAYER_E
Definition at line 39 of file inter_thread_communication.h.
 {
     FIRST_PLAYER_E  = 0,
     SECOND_PLAYER_E = 1,
     MAX_PLAYERS     = 2,
     INVALID_PLAYER_E,
 }player_position_e;
Function Documentation
create_comm_file()
error_e create_comm_file (lock_t * p_lock)
Create a comm file object.
Returns
error_e
Definition at line 383 of file inter_thread_communication.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     FILE* p_comm_file = NULL;
     const errno_t err = fopen_s(&p_comm_file, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, "w");
     if((err == 0 ) && p_comm_file)
     {
         // Created file Succesfuly
         fclose(p_comm_file);
     }
     else
     {
         print_error_msg("Failed to create a new file :( \n");
         e_status = ERROR_FAILED_TO_CREATE_FILE_E;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_CREATE_FILE_E, ERROR_OK, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, and print_error_msg.
Referenced by act_to_msg().
first_or_second_to_play()
player_position_e first_or_second_to_play (lock_t * p_lock, const int file_position)
Parameters
p_lock
file_position
Returns
int -1: error, 1: first play, 2: second player
Definition at line 310 of file inter_thread_communication.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     player_position_e e_player_position = INVALID_PLAYER_E;
     FILE* p_comm_file = NULL;
     int b_is_file_exists = is_file_exists(p_lock);
     if(b_is_file_exists == -1)
     {
         print_error_msg("Failed to verify file existence\n");
     }
     else if(b_is_file_exists == TRUE)
     {
         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Great! File exists, now checking end of file position it\n");
         error_e e_status = LOCK_write_lock(p_lock);
         const errno_t err = fopen_s(&p_comm_file, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, "r");
         if((err == 0) && p_comm_file)
         {
             // Set pointer to last known position
             fseek(p_comm_file, 0, SEEK_END);
             const int new_file_position = ftell(p_comm_file);
             if(new_file_position == file_position)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "I am first player!\n");
                 e_player_position = FIRST_PLAYER_E;
             }
             else if (new_file_position > file_position)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "I am second player :(\n");
                 e_player_position = SECOND_PLAYER_E;
             }
             else
             {
                 print_error_msg("Illegal file position detected!! last file position is %d, while the file position is %d\n", file_position, new_file_position);
             }
             fclose(p_comm_file);
             e_status = LOCK_write_release(p_lock);
             if (e_status != ERROR_OK)
             {
                 print_error_msg("Failed to release communication file from read\n");
             }
         }
         else
         {
             print_error_msg("Error opening file for reading after verifying its existence\n");
         }
     }
     else if(b_is_file_exists == FALSE)
     {
         print_error_msg("FILE DOES NOT EXISIT! When sending a message it is assumed the file exists\n");
     }
     else
     {
         print_error_msg("FATAL! Should never reach this line!\n");
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_player_position;
 }
References DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, FIRST_PLAYER_E, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, INVALID_PLAYER_E, is_file_exists(), LOCK_write_lock, LOCK_write_release, print_error_msg, and SECOND_PLAYER_E.
Referenced by act_to_msg().
is_file_exists()
int is_file_exists (lock_t * p_read_lock)
Returns
int 0 - File does not exist, 1 - File exists, -1 - Fatal error occurred
int
Definition at line 30 of file inter_thread_communication.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     int b_is_file_exists = FALSE;
     error_e e_lock_status = ERROR_OK;
     do
     {
         e_lock_status = LOCK_write_lock(p_read_lock);
         if (e_lock_status != ERROR_OK)
         {
             print_error_msg("Failed to lock communication file for read\n");
         }
         CHECK_AND_BREAK(e_lock_status)
         FILE* p_comm_file = NULL;
         // Reminder: fopen_s return zero on success, otherwise a non-zero value
         const errno_t err = fopen_s(&p_comm_file, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, "r");
         if((err == 0) && p_comm_file)
         {
             // File exists (it was opened successfully for reading)
             b_is_file_exists = TRUE;
             fclose(p_comm_file);
         }
         else
         {
             // File did not open. We assume it is because it does not exist
             // Extreme cases may occure, like someone else changes permissions
             // of the file access in the middle in the run.
             // This is a potentional BUG, but for the scope of this HW
             // we will keep it this way.
             b_is_file_exists = FALSE;
         }
         e_lock_status = LOCK_write_release(p_read_lock);
         if (e_lock_status != ERROR_OK)
         {
             print_error_msg("Failed to release communication file from read\n");
         }
     } while (FALSE);
     if (e_lock_status != ERROR_OK)
     {
         print_error_msg("Failed to lock communication file for read\n");
         b_is_file_exists = -1;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return b_is_file_exists;
 }
References CHECK_AND_BREAK, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, LOCK_write_lock, LOCK_write_release, and print_error_msg.
Referenced by act_to_msg(), first_or_second_to_play(), main(), read_message_using_file(), and send_message_using_file().
read_message_using_file()
error_e read_message_using_file (lock_t * p_lock, char * p_recv_msg, int * msg_size_in_bytes, int * p_file_position)
Parameters
p_lock
p_recv_msg
msg_size_in_bytes
p_file_position
Returns
error_e
Parameters
p_lock
p_msg_to_send
msg_size_in_bytes
p_file_position
Returns
error_e
Definition at line 188 of file inter_thread_communication.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     FILE* p_comm_file = NULL;
     char read_buffer[MAXIMUM_READ_BUFFER_SIZE_IN_BYTES] = {'\0'};
     do
     {
         int b_is_file_exists = is_file_exists(p_lock);
         if(b_is_file_exists == -1)
         {
             print_error_msg("Failed to verify file existence\n");
             e_status = ERROR_FATAL_ERROR_E;
         }
         else if(b_is_file_exists == TRUE)
         {
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Great! File exists, now reading from it\n");
             error_e e_status = LOCK_write_lock(p_lock);
             CHECK_AND_BREAK(e_status);
             const errno_t err = fopen_s(&p_comm_file, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, "r");
             if(err == 0)
             {
                 fseek(p_comm_file, 0, SEEK_END);
                 int end_of_file = ftell(p_comm_file);
                 if((*p_file_position) < end_of_file)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Starting to read from position: %d\n", (*p_file_position));
                     fseek(p_comm_file, (*p_file_position), SEEK_SET);
                     for(int read_idx = 0; read_idx < MAXIMUM_READ_BUFFER_SIZE_IN_BYTES; read_idx++)
                     {
                         int fread_status = fread(&read_buffer[read_idx], sizeof(char), 1, p_comm_file);
                         if (fread_status != 1)
{
                             print_error_msg("Failed to read from file\n");
                         }
                         else
{
                             if(read_buffer[read_idx] == '\n')
{
                                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Finished to read message from file: %s \n", read_buffer);
                                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "The message size is %d\n", read_idx);
                                 if(read_idx > (*msg_size_in_bytes))
{
                                     print_error_msg("Read more bytes than given buffer.\nAllowed size is %d and read %d bytes\n",(*msg_size_in_bytes), read_idx);
                                     e_status = ERROR_INVALID_PARAM_E;
                                 }
                                 else
{
                                     for (int i = 0; i < read_idx; i++)
{
                                         p_recv_msg[i] = read_buffer[i];
                                     }
                                 }
                                 (*msg_size_in_bytes) = read_idx;
                                 break;
                             }
                         }
                     }
                 }
                 else if((*p_file_position) == end_of_file)
                 {
                     // We are at end of file, nothing to read..
                     (*msg_size_in_bytes) = 0;
                 }
                 else
                 {
                     print_error_msg("Last file position %d is greater or equal to end of file %d\n", (*p_file_position), end_of_file)
                 }
                 // Great, now lets update the file position
                 const int new_file_position = ftell(p_comm_file);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Updating file position from %d to %d\n", (*p_file_position), new_file_position);
                 (*p_file_position) = new_file_position;
                 fclose(p_comm_file);
                 e_status = LOCK_write_release(p_lock);
                 if (e_status != ERROR_OK)
                 {
                     print_error_msg("Failed to release communication file from read\n");
                 }
             }
             else
             {
                 print_error_msg("Error opening file for reading after verifying its existence\n");
             }
         }
         else if(b_is_file_exists == FALSE)
         {
             print_error_msg("FILE DOES NOT EXISIT! When reading a message it is assumed the file exists\n");
             e_status = ERROR_FATAL_ERROR_E;
         }
         else
         {
             print_error_msg("FATAL! Should never reach this line!\n");
         }
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FATAL_ERROR_E, ERROR_INVALID_PARAM_E, ERROR_OK, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, is_file_exists(), LOCK_write_lock, LOCK_write_release, MAXIMUM_READ_BUFFER_SIZE_IN_BYTES, and print_error_msg.
Referenced by act_to_msg().
send_message_using_file()
error_e send_message_using_file (lock_t * p_lock, const char *const p_msg_to_send, const int msg_size_in_bytes, int * p_file_position)
Parameters
p_lock
p_msg_to_send
msg_size_in_bytes
p_file_position
Returns
error_e
Definition at line 95 of file inter_thread_communication.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     FILE* p_comm_file = NULL;
     do
     {
         int b_is_file_exists = is_file_exists(p_lock);
         if(b_is_file_exists == -1)
         {
             print_error_msg("Failed to verify file existence\n");
             e_status = ERROR_FATAL_ERROR_E;
         }
         else if(b_is_file_exists == TRUE)
         {
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Great! File exists, now writing to it\n");
             error_e e_status = LOCK_write_lock(p_lock);
             CHECK_AND_BREAK(e_status);
             const errno_t err = fopen_s(&p_comm_file, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, "a");
             if(err == 0)
             {
                 int fwrite_status = fwrite(p_msg_to_send, sizeof(char), msg_size_in_bytes, p_comm_file);
                 if (fwrite_status != msg_size_in_bytes)
                 {
                     print_error_msg("Failed to write to file\n");
                     e_status = ERROR_FAILED_WRITE_TO_OUTPUT_FILE_E;
                 }
                 else
                 {
                     if(p_msg_to_send[msg_size_in_bytes-1] != '\n')
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "The msg was not ending with new line char, attaching it for you\n");
                         int fwrite_new_line_status = fwrite("\n", sizeof(char), 1, p_comm_file);
                         if (fwrite_new_line_status != 1)
{
                             print_error_msg("Failed to write new line to file\n");
                             e_status = ERROR_FAILED_WRITE_TO_OUTPUT_FILE_E;
                         }
                     }
                     // Great, now lets update the file position
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Wrote to file %d bytes\n", fwrite_status);
                     const int new_file_position = ftell(p_comm_file);
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Updating file position from %d to %d\n", (*p_file_position), new_file_position);
                     (*p_file_position) = new_file_position;
                 }
                 fclose(p_comm_file);
                 e_status = LOCK_write_release(p_lock);
                 if (e_status != ERROR_OK)
                 {
                     print_error_msg("Failed to release communication file from read\n");
                 }
             }
             else
             {
                 print_error_msg("Error opening file for writing after verifying its existence\n");
             }
         }
         else if(b_is_file_exists == FALSE)
         {
             print_error_msg("FILE DOES NOT EXISIT! When sending a message it is assumed the file exists\n");
             e_status = ERROR_FATAL_ERROR_E;
         }
         else
         {
             print_error_msg("FATAL! Should never reach this line!\n");
         }
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_WRITE_TO_OUTPUT_FILE_E, ERROR_FATAL_ERROR_E, ERROR_OK, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, is_file_exists(), LOCK_write_lock, LOCK_write_release, and print_error_msg.