EX4: lock.c File Reference
lock.c File Reference
Lock module allows easy useage of the readers-writers algorithm for syncronization described at recitation 7.
#include "lock.h"
Functions
lock_t * LOCK_initialize_lock (void)
Initialize a lock struct, All three sync object are created but not assigned to anyone yet. Returns a pointer to the allocated struct.
error_e LOCK_read_lock (lock_t *const p_lock)
Lock a resource (can be what ever resource you want) for readinging. That is, any number of readers can access the resource, but no writers are allowed.
error_e LOCK_read_release (lock_t *const p_lock)
Release the readers lock.
error_e LOCK_write_lock (lock_t *const p_lock)
Lock a resource for writing. That is, exclusive access, to a specific resource. No other readers or writers can read or wite to it.
error_e LOCK_write_release (lock_t *const p_lock)
Release the write lock.
error_e LOCK_destroy_lock (lock_t **pp_lock)
Close all handles of the sync objects. Free the allocated memory, and set the pointer to the struct to NULL.
Detailed Description
Lock module allows easy useage of the readers-writers algorithm for syncronization described at recitation 7.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file lock.c.
Function Documentation
LOCK_destroy_lock()
error_e LOCK_destroy_lock (lock_t ** pp_lock)
Close all handles of the sync objects. Free the allocated memory, and set the pointer to the struct to NULL.
Parameters
[in] p_lock
Returns
error_e
Definition at line 275 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     if(NULL == pp_lock)
     {
         print_error_msg("Called Destroy lock with NULL pointer");
         e_status = ERROR_NULL_POINTER_E;
     }
     else
     {
         lock_t *p_lock = (*pp_lock);
         if(p_lock)
         {
             if(p_lock->critical_section_mutex_handle)
             {
                 CloseHandle(p_lock->critical_section_mutex_handle);
                 p_lock->critical_section_mutex_handle = NULL;
                 DEBUG_PRINT(DEBUG_LEVEL_THREE, "Released critical section handle\n");
             }
             if(p_lock->turnstile_mutex_handle)
             {
                 CloseHandle(p_lock->turnstile_mutex_handle);
                 p_lock->turnstile_mutex_handle = NULL;
                 DEBUG_PRINT(DEBUG_LEVEL_THREE, "Released turnstile handle\n");
             }
             if(p_lock->readers_semaphore_handle)
             {
                 CloseHandle(p_lock->readers_semaphore_handle);
                 p_lock->readers_semaphore_handle = NULL;
                 DEBUG_PRINT(DEBUG_LEVEL_THREE, "Released semaphore handle\n");
             }
             free(p_lock);
             (*pp_lock) = NULL;
         }
         else
         {
             DEBUG_PRINT(DEBUG_LEVEL_THREE, "Called destroy lock on an un-inialized lock\n");
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References lock_s::critical_section_mutex_handle, DEBUG_LEVEL_THREE, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_NULL_POINTER_E, ERROR_OK, print_error_msg, lock_s::readers_semaphore_handle, and lock_s::turnstile_mutex_handle.
Referenced by LOCK_initialize_lock(), and main().
LOCK_initialize_lock()
lock_t* LOCK_initialize_lock (void)
Initialize a lock struct, All three sync object are created but not assigned to anyone yet. Returns a pointer to the allocated struct.
Returns
lock_t*
Definition at line 25 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     lock_t *p_lock = NULL;
     error_e e_status = ERROR_OK;
     do
     {
         // Allocate memory for lock
         p_lock = (lock_t *)malloc(sizeof(lock_t));
         if (NULL == p_lock)
         {
             print_error_msg("Failed to allocate memory for lock\n");
             e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
         }
         CHECK_AND_BREAK(e_status);
         p_lock->turnstile_mutex_handle = NULL;
         p_lock->critical_section_mutex_handle = NULL;
         p_lock->readers_semaphore_handle = NULL;
         p_lock->readers = 0L;
         // Create turnstile
         p_lock->turnstile_mutex_handle = CreateMutex(
             NULL,                       /* default security attributes */
             FALSE,                      /* initially not owned */
             NULL); /* unnamed mutex L"turnstile_mutex_handle"*/
         if (p_lock->turnstile_mutex_handle == NULL)
         {
             print_error_msg("Error when creating mutex: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_CREATE_MUTEX_E;
         }
         CHECK_AND_BREAK(e_status);
         p_lock->critical_section_mutex_handle = CreateMutex(
             NULL,                       /* default security attributes */
             FALSE,                      /* initially not owned */
             NULL); /* unnamed mutex L"critical_section_mutex_handle"*/
         if (p_lock->critical_section_mutex_handle == NULL)
         {
             print_error_msg("Error when creating mutex: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_CREATE_MUTEX_E;
         }
         CHECK_AND_BREAK(e_status);
         p_lock->readers_semaphore_handle = CreateSemaphore(
             NULL,                         // default security attributes
             1,                            // initial count
             1,                            // maximum count
             NULL); // unnamed semaphore L"readers_semaphore_handle
         DEBUG_PRINT(DEBUG_LEVEL_FOUR, "readers_semaphore_handle was created\n");
         if (NULL == p_lock->readers_semaphore_handle || INVALID_HANDLE_VALUE == p_lock->readers_semaphore_handle)
         {
             print_error_msg("CreateSemaphore error: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_CREATE_SEMAPHORE_E;
         }
         CHECK_AND_BREAK(e_status);
         /* code */
     } while (FALSE);
     if(ERROR_OK != e_status)
     {
         print_error_msg("Very bad error occurred, failed to initilize lock module\n");
         e_status = LOCK_destroy_lock(&p_lock);
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return p_lock;
 }
References CHECK_AND_BREAK, lock_s::critical_section_mutex_handle, DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_ALLOCATE_MEMORY_E, ERROR_FAILED_TO_CREATE_MUTEX_E, ERROR_FAILED_TO_CREATE_SEMAPHORE_E, ERROR_OK, LOCK_destroy_lock(), print_error_msg, lock_s::readers, lock_s::readers_semaphore_handle, and lock_s::turnstile_mutex_handle.
Referenced by main().
LOCK_read_lock()
error_e LOCK_read_lock (lock_t *const p_lock)
Lock a resource (can be what ever resource you want) for readinging. That is, any number of readers can access the resource, but no writers are allowed.
Parameters
[in] p_lock
Returns
queue_elem_t
Definition at line 109 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         DWORD wait_status = WaitForSingleObject(p_lock->turnstile_mutex_handle, ONE_MINUTE_IN_MILLISECONDS);
         CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
         DWORD release_status = ReleaseMutex(p_lock->turnstile_mutex_handle);
         if(FALSE == release_status)
         {
             print_error_msg("Failed to release turnstile mutex with error code: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_RELEASE_MUTEX_E;
         }
         CHECK_AND_BREAK(release_status);
         wait_status = WaitForSingleObject(p_lock->critical_section_mutex_handle, TEN_SECONDS_IN_MILLISECONDS);
         CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
         DEBUG_PRINT(DEBUG_LEVEL_NINE, "Starting critical section\n");
         (p_lock->readers) += 1;
         if (1 == (p_lock->readers))
         {
             wait_status = WaitForSingleObject(p_lock->readers_semaphore_handle, TEN_SECONDS_IN_MILLISECONDS);
             CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
         }
         DEBUG_PRINT(DEBUG_LEVEL_NINE, "Finished critical section\n");
         release_status = ReleaseMutex(p_lock->critical_section_mutex_handle);
         if(FALSE == release_status)
         {
             print_error_msg("Failed to release turnstile mutex with error code: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_RELEASE_MUTEX_E;
         }
         CHECK_AND_BREAK(release_status);
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL, lock_s::critical_section_mutex_handle, DEBUG_LEVEL_NINE, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_RELEASE_MUTEX_E, ERROR_OK, ONE_MINUTE_IN_MILLISECONDS, print_error_msg, lock_s::readers, lock_s::readers_semaphore_handle, TEN_SECONDS_IN_MILLISECONDS, and lock_s::turnstile_mutex_handle.
LOCK_read_release()
error_e LOCK_read_release (lock_t *const p_lock)
Release the readers lock.
Parameters
[in] p_lock
Returns
error_e
Definition at line 165 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         DWORD wait_status = WaitForSingleObject(p_lock->critical_section_mutex_handle, ONE_SECOND_IN_MILLISECONDS);
         CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
         (p_lock->readers) -= 1;
         if (0 == (p_lock->readers))
         {
             DWORD release_status = ReleaseSemaphore(p_lock->readers_semaphore_handle, 1, NULL);
             if(FALSE == release_status)
             {
                 print_error_msg("Failed to release readers semaphore with error code: %d\n", GetLastError());
                 e_status = ERROR_FAILED_TO_RELEASE_SEMAPHORE_E;
             }
             CHECK_AND_BREAK(e_status);
         }
         DWORD release_status = ReleaseMutex(p_lock->critical_section_mutex_handle);
         if(FALSE == release_status)
         {
             print_error_msg("Failed to release mutex with error code: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_RELEASE_MUTEX_E;
         }
         CHECK_AND_BREAK(e_status);
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL, lock_s::critical_section_mutex_handle, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_RELEASE_MUTEX_E, ERROR_FAILED_TO_RELEASE_SEMAPHORE_E, ERROR_OK, ONE_SECOND_IN_MILLISECONDS, print_error_msg, lock_s::readers, and lock_s::readers_semaphore_handle.
LOCK_write_lock()
error_e LOCK_write_lock (lock_t *const p_lock)
Lock a resource for writing. That is, exclusive access, to a specific resource. No other readers or writers can read or wite to it.
Parameters
[in] p_lock
Returns
error_e
Definition at line 211 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         DWORD wait_status = WaitForSingleObject(p_lock->turnstile_mutex_handle, ONE_MINUTE_IN_MILLISECONDS);
         CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
         wait_status = WaitForSingleObject(p_lock->readers_semaphore_handle, ONE_MINUTE_IN_MILLISECONDS);
         CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL(wait_status);
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_WAIT_FOR_OBJECT_STATAUS_BREAK_ON_FAIL, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, ONE_MINUTE_IN_MILLISECONDS, lock_s::readers_semaphore_handle, and lock_s::turnstile_mutex_handle.
LOCK_write_release()
error_e LOCK_write_release (lock_t *const p_lock)
Release the write lock.
Parameters
[in] p_lock
Returns
error_e
Definition at line 238 of file lock.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         DWORD release_status = ReleaseMutex(p_lock->turnstile_mutex_handle);
         if(FALSE == release_status)
         {
             print_error_msg("Failed to release turnstile mutex with error code: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_RELEASE_MUTEX_E;
         }
         CHECK_AND_BREAK(e_status);
         release_status =ReleaseSemaphore(p_lock->readers_semaphore_handle, 1, NULL);
         if(FALSE == release_status)
         {
             print_error_msg("Failed to release readers semaphore with error code: %d\n", GetLastError());
             e_status = ERROR_FAILED_TO_RELEASE_SEMAPHORE_E;
         }
         CHECK_AND_BREAK(e_status);
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_RELEASE_MUTEX_E, ERROR_FAILED_TO_RELEASE_SEMAPHORE_E, ERROR_OK, print_error_msg, lock_s::readers_semaphore_handle, and lock_s::turnstile_mutex_handle.