EX4: queue_ext.h File Reference
queue_ext.h File Reference
All exposed functions and types to be used by someone who wants to call the Queue module.
#include <Windows.h>
#include "common_types.h"
#include "trace.h"
Data Structures
struct queue_elem_s
An element of FIFO queue. Hold on a generic data, here limited to a DWORD type. And a pointer to the following element in the queue. Last element is pointing to NULL.
struct queue_s
A queue object. Has pointer to last and first elements in the queue. Also hold a counter on the number of element, this is no an obligatory property, but it allows better dubging and can be useful in other cases. The queue is considered valid when count and first and last element state are matching. That is, if count equals to zero, both first and last element must point to NULL. Overwise, when count is one, both first and last element must point to the same element. Otherwise, when count is gretaer than one, each has to point to another element.
Macros
#define NULL_QUEUE_ELEMENT {.data = 0L, .p_next = NULL,}
#define DEBUG_PRINT_QUEUE_STATUS(...) QUEUE_print_queue(__VA_ARGS__)
Typedefs
typedef struct queue_elem_s queue_elem_t
typedef struct queue_s queue_t
A queue object. Has pointer to last and first elements in the queue. Also hold a counter on the number of element, this is no an obligatory property, but it allows better dubging and can be useful in other cases. The queue is considered valid when count and first and last element state are matching. That is, if count equals to zero, both first and last element must point to NULL. Overwise, when count is one, both first and last element must point to the same element. Otherwise, when count is gretaer than one, each has to point to another element.
Functions
queue_t * QUEUE_initialize_queue (void)
Initiliaze a new queue struct. The new queue will be initialized as empty, that is, both its p_last_elem and p_first_elem element will point to NULL. is empty is set to true. and the count of elements is set to 0. Note: This function will allocate memory, which must be freed by the caller.
queue_elem_t QUEUE_top (queue_t *p_queue)
Given a queue, return the top element of the queue. On fail: reutrn a "NULL Queue element", that is, data is INVALID_INTEGER_VALUE and next is NULL. Can fail for two reasons: 1) Given a NULL queue pointer. 2) Called on an empty queue.
error_e QUEUE_pop (queue_t *p_queue)
Removed the top queue element from the queue. If called on empty queue does nothing, but return a return value indicating that. Fails when called with a NULL pointer to queue.
error_e QUEUE_push (queue_t *p_queue, queue_elem_t new_element)
Add a queue element to queue as the p_last_elem element, will also be the p_first_elem if queue was empty.
BOOL QUEUE_empty (queue_t *p_queue)
Returns true if the queue is empty and false otherwise. (Also checks the validity of the queuewhen accessing it).
error_e QUEUE_destroy_queue (queue_t **p_queue)
Frees all elements in the queue, then free the queue struct and sets it to NULL.
void QUEUE_print_queue (queue_t *p_queue)
Print all elements in queue.
Detailed Description
All exposed functions and types to be used by someone who wants to call the Queue module.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file queue_ext.h.
Macro Definition Documentation
DEBUG_PRINT_QUEUE_STATUS
#define DEBUG_PRINT_QUEUE_STATUS (...) QUEUE_print_queue(__VA_ARGS__)
Definition at line 31 of file queue_ext.h.
NULL_QUEUE_ELEMENT
#define NULL_QUEUE_ELEMENT {.data = 0L, .p_next = NULL,}
Definition at line 27 of file queue_ext.h.
Typedef Documentation
queue_elem_t
typedef struct queue_elem_s queue_elem_t
Definition at line 1 of file queue_ext.h.
queue_t
typedef struct queue_s queue_t
A queue object. Has pointer to last and first elements in the queue. Also hold a counter on the number of element, this is no an obligatory property, but it allows better dubging and can be useful in other cases. The queue is considered valid when count and first and last element state are matching. That is, if count equals to zero, both first and last element must point to NULL. Overwise, when count is one, both first and last element must point to the same element. Otherwise, when count is gretaer than one, each has to point to another element.
Function Documentation
QUEUE_destroy_queue()
error_e QUEUE_destroy_queue (queue_t ** p_queue)
Frees all elements in the queue, then free the queue struct and sets it to NULL.
Parameters
[in] p_queue
Returns
error_e
Definition at line 234 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     if(FALSE == QUEUE_is_valid_queue(*p_queue))
     {
         print_error_msg("Not a valid queue, can't destroy it.\n");
         e_status = ERROR_INVALID_QUEUE_E;
     }
     else
     {
         if(FALSE == QUEUE_empty(*p_queue))
         {
             queue_elem_t *p_curr_elem = (*p_queue)->p_first_elem;
             while(p_curr_elem->p_next)
             {
                 queue_elem_t *p_temp_elem = p_curr_elem->p_next;
                 free(p_curr_elem);
                 DEBUG_PRINT(DEBUG_LEVEL_THREE, "Just freed a queue element! :)\n");
                 p_curr_elem = p_temp_elem;
             }
             free(p_curr_elem);
             DEBUG_PRINT(DEBUG_LEVEL_THREE, "Just freed a queue element! :)\n");
         }
         free(*p_queue);
         DEBUG_PRINT(DEBUG_LEVEL_THREE, "Just freed the queue pointer! :)\n");
         (*p_queue) = NULL;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_LEVEL_THREE, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_QUEUE_E, ERROR_OK, queue_elem_s::p_next, print_error_msg, QUEUE_empty(), and QUEUE_is_valid_queue().
QUEUE_empty()
BOOL QUEUE_empty (queue_t * p_queue)
Returns true if the queue is empty and false otherwise. (Also checks the validity of the queuewhen accessing it).
Parameters
[in] p_queue
Returns
BOOL
Returns true if the queue is empty and false otherwise. (Also checks the validity of the queuewhen accessing it).
Parameters
[in] p_queue
Returns
BOOL
Definition at line 206 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     BOOL b_is_empty = TRUE;
     if(QUEUE_is_valid_queue(p_queue))
     {
         if(p_queue->p_first_elem)
         {
             b_is_empty = FALSE;
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return b_is_empty;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, queue_s::p_first_elem, and QUEUE_is_valid_queue().
Referenced by QUEUE_destroy_queue().
QUEUE_initialize_queue()
queue_t* QUEUE_initialize_queue (void)
Initiliaze a new queue struct. The new queue will be initialized as empty, that is, both its p_last_elem and p_first_elem element will point to NULL. is empty is set to true. and the count of elements is set to 0. Note: This function will allocate memory, which must be freed by the caller.
Returns
queue_t* if failed, reutns NULL.
Definition at line 31 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     queue_t *p_queue = malloc(sizeof(queue_t));
     if(NULL == p_queue)
     {
         print_error_msg("Failed to allocate memory for queue\n");
     }
     else
     {
         p_queue->count         = 0L;
         p_queue->p_first_elem  = NULL;
         p_queue->p_last_elem   = NULL;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return p_queue;
 }
References queue_s::count, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, queue_s::p_first_elem, queue_s::p_last_elem, and print_error_msg.
QUEUE_pop()
error_e QUEUE_pop (queue_t * p_queue)
Removed the top queue element from the queue. If called on empty queue does nothing, but return a return value indicating that. Fails when called with a NULL pointer to queue.
Parameters
[in] p_queue
Returns
error_e
Definition at line 103 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     if(FALSE == QUEUE_is_valid_queue(p_queue))
     {
         print_error_msg("Invalid queue.\n");
         e_status = ERROR_INVALID_QUEUE_E;
     }
     else
     {
         if(p_queue->p_first_elem)
         {
             queue_elem_t *p_temp_first_elem = p_queue->p_first_elem;
             p_queue->p_first_elem = p_temp_first_elem->p_next;
             free(p_temp_first_elem);
             p_queue->count--;
         }
         else
         {
             DEBUG_PRINT(DEBUG_LEVEL_LOWEST, "Called on an empty queue, nothing to pop.\n");
             e_status = ERROR_CALLED_ON_EMPTY_QUEUE_E;
         }
         if(0 == p_queue->count)
         {
             p_queue->p_first_elem = NULL;
             p_queue->p_last_elem = NULL;
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References queue_s::count, DEBUG_LEVEL_LOWEST, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_CALLED_ON_EMPTY_QUEUE_E, ERROR_INVALID_QUEUE_E, ERROR_OK, queue_s::p_first_elem, queue_s::p_last_elem, queue_elem_s::p_next, print_error_msg, and QUEUE_is_valid_queue().
QUEUE_print_queue()
void QUEUE_print_queue (queue_t * p_queue)
Print all elements in queue.
Parameters
p_queue
Definition at line 281 of file queue.c.
 {
     if(QUEUE_is_valid_queue(p_queue))
     {
         HANDLE console_handle = GetStdHandle(STD_OUTPUT_HANDLE);
         SetConsoleTextAttribute(console_handle, GREEN__CONSOLE_COLOR_CODE);
         printf("=======================================\n");
         printf("=========Queue Status==================\n");
         printf("=======================================\n");
         queue_elem_t *p_queue_elem = p_queue->p_first_elem;
         for(DWORD queue_idx = 0; queue_idx < p_queue->count; queue_idx++)
         {
             printf("Item located at: %3d, data: %10d\n", queue_idx, p_queue_elem->data);
             p_queue_elem = p_queue_elem->p_next;
         }
         printf("=======================================\n");
         SetConsoleTextAttribute(console_handle, WHITE__CONSOLE_COLOR_CODE);
     }
 }
References queue_s::count, queue_elem_s::data, GREEN__CONSOLE_COLOR_CODE, queue_s::p_first_elem, queue_elem_s::p_next, QUEUE_is_valid_queue(), and WHITE__CONSOLE_COLOR_CODE.
QUEUE_push()
error_e QUEUE_push (queue_t * p_queue, queue_elem_t new_element)
Add a queue element to queue as the p_last_elem element, will also be the p_first_elem if queue was empty.
Parameters
[in] p_queue
[in] new_element
Returns
error_e
If the queue is empty, that means both p_last_elem and p_first_elem elements should point to NULL. In that case, we need update both the p_last_elem and p_first_elem to point to the new element. If the queue is not empty we want the current p_last_elem element to point to our p_last_elem element, and update the queue p_last_elem element with the new element.
So in both cases (empty or not) the queue p_last_elem pointer has to point to new element, and the count increases.
Definition at line 151 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     if(FALSE == QUEUE_is_valid_queue(p_queue))
     {
         print_error_msg("Invalid queue.\n");
         e_status = ERROR_INVALID_QUEUE_E;
     }
     else
     {
         queue_elem_t* p_new_last_elem;
         e_status = QUEUE_create_queue_element(new_element.data, &p_new_last_elem);
         if(ERROR_OK == e_status)
         {
             if(p_queue->p_last_elem)
             {
                 p_queue->p_last_elem->p_next = p_new_last_elem;
             }
             else
             {
                 p_queue->p_first_elem = p_new_last_elem;
             }
             p_queue->p_last_elem = p_new_last_elem;
             p_queue->count++;
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References queue_s::count, queue_elem_s::data, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_QUEUE_E, ERROR_OK, queue_s::p_first_elem, queue_s::p_last_elem, queue_elem_s::p_next, print_error_msg, QUEUE_create_queue_element(), and QUEUE_is_valid_queue().
QUEUE_top()
queue_elem_t QUEUE_top (queue_t * p_queue)
Given a queue, return the top element of the queue. On fail: reutrn a "NULL Queue element", that is, data is INVALID_INTEGER_VALUE and next is NULL. Can fail for two reasons: 1) Given a NULL queue pointer. 2) Called on an empty queue.
Parameters
[in] p_queue
Returns
queue_elem_t
Definition at line 66 of file queue.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     queue_elem_t top_queue_elem = {.data = INVALID_INTEGER_VALUE, .p_next = NULL};
     if(FALSE == QUEUE_is_valid_queue(p_queue))
     {
         print_error_msg("Invalid queue.\n");
     }
     else
     {
         if(p_queue->p_first_elem)
         {
             top_queue_elem = (*(p_queue->p_first_elem));
         }
         else
         {
             print_error_msg("Called on an empty queue.\n");
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return top_queue_elem;
 }
References queue_elem_s::data, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, INVALID_INTEGER_VALUE, queue_s::p_first_elem, print_error_msg, and QUEUE_is_valid_queue().