EX4: send_recv_messages_ext.h File Reference
send_recv_messages_ext.h File Reference
#include <winsock2.h>
#include <ws2tcpip.h>
#include "common_types.h"
#include "read_write_msg_ext.h"
Functions
error_e send_msg (const message_type_e e_msg_type, char *msg_parameters[(4)], SOCKET p_transmit_socket)
error_e receive_msg (SOCKET recv_socket, msg_parameters_t *msg_params)
error_e wait_for_socket_shutdown (SOCKET recv_socket)
error_e send_socket_shutdown (SOCKET recv_socket)
Function Documentation
receive_msg()
error_e receive_msg (SOCKET recv_socket, msg_parameters_t * msg_params)
Parameters
recv_socket
msg_params
Returns
error_e
Definition at line 33 of file socket_send_recv_tools.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     // Input Check
     char* p_received_string = NULL;
     transfer_results_t  recv_res = SOCKET_receive_string(&p_received_string , recv_socket);
     if ( recv_res == TRNS_FAILED )
     {
         print_error_msg("Service socket error while reading, closing thread.\n" );
         closesocket( recv_socket );
         e_status = ERROR_FATAL_ERROR_E;
     }
     else if ( recv_res == TRNS_DISCONNECTED )
     {
         print_error_msg( "Connection closed while reading, closing thread.\n" );
         closesocket( recv_socket );
         e_status = ERROR_CLIENT_DISCONNECTED_UNEXPECTEDLY_E;
     }
     else
     {
         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Got string : %s\n", p_received_string);
     }
     CHECK_AND_RETURN(e_status);
     e_status = message_read(msg_params, p_received_string);
     if(p_received_string)
     {
         free(p_received_string);
         p_received_string = NULL;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_RETURN, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_CLIENT_DISCONNECTED_UNEXPECTEDLY_E, ERROR_FATAL_ERROR_E, ERROR_OK, message_read(), print_error_msg, SOCKET_receive_string(), TRNS_DISCONNECTED, and TRNS_FAILED.
Referenced by main(), and server_client_comm_thread().
send_msg()
error_e send_msg (const message_type_e e_msg_type, char * msg_parameters[(4)], SOCKET p_transmit_socket)
Parameters
e_msg_type
msg_parameters
p_transmit_socket
Returns
error_e
Referenced by act_to_msg(), and main().
send_socket_shutdown()
error_e send_socket_shutdown (SOCKET recv_socket)
Parameters
recv_socket
Returns
error_e
Definition at line 179 of file socket_send_recv_tools.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     int shutdown_status = shutdown(recv_socket, SD_SEND);
     if (shutdown_status == SOCKET_ERROR)
     {
         print_error_msg("shutdown failed with error: %d\n", WSAGetLastError());
         e_status = ERROR_SOCKET_SHUTDOWN_SEND_ERROR_E;
     }
     closesocket(recv_socket);
     // WSACleanup();
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, ERROR_SOCKET_SHUTDOWN_SEND_ERROR_E, and print_error_msg.
Referenced by act_to_msg().
wait_for_socket_shutdown()
error_e wait_for_socket_shutdown (SOCKET recv_socket)
Parameters
recv_socket
Returns
error_e
Definition at line 135 of file socket_send_recv_tools.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     // Receive until the peer closes the connection
     error_e e_status = ERROR_OK;
     char recv_buffer[MAX_MSG_SIZE];
     int recv_stat = -1;
     do {
         recv_stat = recv(recv_socket, recv_buffer, MAX_MSG_SIZE, 0);
         if ( recv_stat > 0 )
         {
             print_error_msg("wait_for_socket_shutdown received data instead of shutdown\n");
             DEBUG_PRINT(DEBUG_LEVEL_TWO,"Number of bytes received: %d\n", recv_stat);
             DEBUG_PRINT(DEBUG_LEVEL_TWO,"Bytes received: %s\n", recv_buffer);
             e_status = ERROR_SOCKET_SHUTDOWN_RECEIVED_DATA_E;
         }
         else if ( recv_stat == 0 )
         {
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Connection closed\n");
             closesocket(recv_socket);
         }
         else
         {
             print_error_msg("recv failed with error: %d\n", WSAGetLastError());
             e_status = ERROR_FATAL_ERROR_E;
         }
     } while( recv_stat > 0 );
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FATAL_ERROR_E, ERROR_OK, ERROR_SOCKET_SHUTDOWN_RECEIVED_DATA_E, MAX_MSG_SIZE, and print_error_msg.
Referenced by act_to_msg(), and main().