EX4: server.c File Reference
server.c File Reference
TODO: Fill.
#include "server.h"
Functions
int main (int argc, char *argv[])
static DWORD server_client_comm_thread (client_handler_params_t *p_params)
static error_e act_to_msg (SOCKET connection_socket, msg_parameters_t input_msg_params, lock_t *p_players_num_lock, int *p_last_position_in_file, char my_four_digits_number[MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS], int *p_created_comm_file, player_position_e *p_my_index, player_position_e *p_opponent_index)
static int find_first_unused_thread_slot (const HANDLE a_thread_handles[(3)])
static error_e close_signaled_threads (HANDLE a_thread_handles[(3)])
static DWORD exit_thread (void *unused_param)
Waits for user input, if input string is "exit", gracefully disconnects the clients and shuts down the server.
static error_e set_player_data (lock_t *p_lock, const player_position_e e_player_index, const char player_name[])
static error_e clear_player_data (lock_t *p_lock, const player_position_e e_player_index)
static player_position_e get_first_free_player_position (lock_t *p_lock, player_position_e *p_avl_positon)
static error_e set_opponent_index (const player_position_e e_my_idx, player_position_e *p_opponent_index)
static error_e increase_connected_players_by_one (lock_t *p_lock)
static error_e decrease_connected_players_by_one (lock_t *p_lock)
static int get_number_of_connected_players (lock_t *p_lock)
static int my_name_is_unique (lock_t *p_lock, const char my_username[])
static int get_disconnection_status_read_and_clear (lock_t *p_lock)
static error_e set_disconnection_status (lock_t *p_lock)
Variables
static HANDLE g_exit_event = NULL
Event to signal all threads the server admistrator asked to close the server.
static HANDLE g_first_event = NULL
When signaled, means that "First" player may read/wrtie to file.
static HANDLE g_second_event = NULL
When signaled, means that "Second" player may read/wrtie to file.
static int g_number_of_connected_players = 0
Number of connected players, that means they received a SERVER_APPROVED message.
static int g_is_player_got_disconnect = FALSE
Indicated if a player god disconnected.
static char g_players_names [MAX_PLAYERS][USERNAME_MAX_LEGNTH_STRING] = {'\0'}
static int g_players_playing [MAX_PLAYERS] = {0}
Detailed Description
TODO: Fill.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file server.c.
Function Documentation
act_to_msg()
static error_e act_to_msg (SOCKET connection_socket, msg_parameters_t input_msg_params, lock_t * p_players_num_lock, int * p_last_position_in_file, char my_four_digits_number[MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS], int * p_created_comm_file, player_position_e * p_my_index, player_position_e * p_opponent_index) static
Parameters
connection_socket
input_msg_params
p_players_num_lock
Returns
error_e
When there is a timeout waiting for other player. We want to keep our game_session log, until this client disconnects from server.
Definition at line 398 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     int current_num_of_connected_players = -1;
     char* out_msg_parameters[MAX_NUMBER_OF_PARAMETERS_IN_MSG] = { 0 };
     set_output_msg_parameters_to_null();
     char p_output_msg_buffer[MAX_MSG_SIZE] = {'\0'};
     game_state_e e_game_state = GAME_STATE_INVALID_STATE_E;
     do
     {
         /* Input Check*/
         switch (input_msg_params.e_msg_type)
         {
         case CLIENT_REQUEST:
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "SERVER is acting to %s msg ==\n", get_msg_string(CLIENT_REQUEST));
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Client Number is: %s\n", input_msg_params.username);
             int approve_flag = SERVER_DO_NOT_APPROVE;
             current_num_of_connected_players = get_number_of_connected_players(p_players_num_lock);
             if((current_num_of_connected_players == 0) || (current_num_of_connected_players == 1))
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "There are no more players or only one connected\n");
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Determine my index by checking database\n");
                 e_status = get_first_free_player_position(p_players_num_lock, p_my_index);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "My index is: %d\n", (*p_my_index));
                 CHECK_AND_BREAK(e_status);
                 if((*p_my_index) != INVALID_PLAYER_E)
                 {
                     e_status = set_opponent_index((*p_my_index), p_opponent_index);
                     CHECK_AND_BREAK(e_status);
                     if(is_file_exists(p_players_num_lock) == FALSE)
                     {
                         // Need to create a new file
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Creating a new game session file for communication\n");
                         e_status = create_comm_file(p_players_num_lock);
                         CHECK_AND_BREAK(e_status);
                         (*p_created_comm_file) = TRUE;
                     }
                     if(my_name_is_unique(p_players_num_lock, input_msg_params.username) == TRUE)
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Set player data to global database: index %d as valid and name as %s\n", (*p_my_index), input_msg_params.username);
                         e_status = set_player_data(p_players_num_lock, (*p_my_index), input_msg_params.username);
                         approve_flag = SERVER_APPROVE;
                     }
                     else
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Shame, your username <%s> is already taken\n", input_msg_params.username);
                         out_msg_parameters[0] = "Username is already taken, please logout and try with new name\n";
                         approve_flag = SERVER_DO_NOT_APPROVE;
                     }
                 }
                 else
                 {
                     print_error_msg("Threr is a bug, only one or none other users, but can't get a valid player index");
                     approve_flag = SERVER_DO_NOT_APPROVE;
                 }
             }
             else
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "There are more two other players connected to server\n");
                 out_msg_parameters[0] = "Server is full. You may want to try later...\n";
                 approve_flag = SERVER_DO_NOT_APPROVE;
             }
             CHECK_AND_BREAK(e_status);
             if (approve_flag == SERVER_DO_NOT_APPROVE)
             {
                 e_status = send_msg(SERVER_DENIED, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = send_socket_shutdown(connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = ERROR_DENIED_CLIENT_E;
             }
             else if (approve_flag == SERVER_APPROVE)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Increased number of connected players.\n");
                 increase_connected_players_by_one(p_players_num_lock);
                 e_status = send_msg(SERVER_APPROVED, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = send_msg(SERVER_MAIN_MENU, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
             }
             else
             {
                 print_error_msg("Invalid flow! Program should not reach this point!\n");
                 e_status = ERROR_FATAL_ERROR_E;
             }
             break;
         case CLIENT_VERSUS:
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "SERVER is acting to %s msg ==\n", get_msg_string(CLIENT_VERSUS));
             current_num_of_connected_players = get_number_of_connected_players(p_players_num_lock);
             if (current_num_of_connected_players < MAX_PLAYERS)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Not enough players.. \n");
                 // TODO: might watn to change this status, but for now it is good enough
                 e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
             }
             CHECK_AND_BREAK(e_status);
             // Barrier for other thread to signal we are at this stage
             // Need to
             if((*p_my_index) == FIRST_PLAYER_E)
             {
                 // I am the first player leeting second player know I am ready to play
                 SetEvent(g_second_event);
                 DWORD wait_stat = WaitForSingleObject(g_first_event, 2 * FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Succesfully wait for other thread\n");
                 }
                 else
                 {
                     ResetEvent(g_second_event);
                     e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                 }
                 CHECK_AND_BREAK(e_status);
             }
             else if((*p_my_index) == SECOND_PLAYER_E)
             {
                 /* I am the second player, letting first play know i am ready to play */
                 SetEvent(g_first_event);
                 DWORD wait_stat = WaitForSingleObject(g_second_event, 2 * FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Succesfully wait for other thread\n");
                 }
                 else
                 {
                     ResetEvent(g_first_event);
                     e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                 }
             }
             else
             {
                 /* ERROR */
             }
             CHECK_AND_BREAK(e_status);
             // Get opponent username
             out_msg_parameters[0] = g_players_names[((*p_opponent_index))];
             e_status = send_msg(SERVER_INVITE, out_msg_parameters, connection_socket);
             CHECK_AND_BREAK(e_status);
             e_status = send_msg(SERVER_SETUP_REQUEST, out_msg_parameters, connection_socket);
             CHECK_AND_BREAK(e_status);
             break;
         case CLIENT_SETUP:
             // Check if we got here legally
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "SERVER is acting to %s msg ==\n", get_msg_string(CLIENT_SETUP));
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Client Number is: %s\n", input_msg_params.four_digits_number);
             // Save user number somewhere.
             for(int idx = 0; idx < MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS; idx++)
             {
                 my_four_digits_number[idx] = input_msg_params.four_digits_number[idx];
             }
             // Send move request
             e_status = send_msg(SERVER_PLAYER_MOVE_REQUEST, out_msg_parameters, connection_socket);
             CHECK_AND_BREAK(e_status);
             break;
         case CLIENT_PLAYER_MOVE:
             // Check if we got here legally
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "SERVER is acting to %s msg ==\n", get_msg_string(CLIENT_PLAYER_MOVE));
             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Client guess is: %s\n", input_msg_params.four_digits_number);
             int opponent_got_disconnected = get_disconnection_status_read_and_clear(p_players_num_lock);
             if(opponent_got_disconnected == TRUE)
             {
                 e_status = send_msg(SERVER_OPPONENT_QUIT, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "The opponent quited unexpectdly\n");
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Starting thread communication cleanup\n");
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Delete game session file\n");
                 if(is_file_exists(p_players_num_lock) == TRUE)
                 {
                     if (remove(INTER_THREAD_COMMUNICATION_FILE_NAME_STRING) == 0)
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Deleted %s successfully\n", INTER_THREAD_COMMUNICATION_FILE_NAME_STRING);
                     }
                     else
                     {
                         print_error_msg("Failed to delete file\n")
                     }
                 }
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Clear file position pointer\n");
                 (*p_last_position_in_file) = 0;
                 // Opponent quited
                 e_status = send_msg(SERVER_MAIN_MENU, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 break;
             }
             char result[MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS + 1] = { 0 };
             char other_player_bulls_cows[MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS + 1] = { 0 };
             char opponent_guess[6] = {'\0'};
             // Who was first to react on for the digits request
             player_position_e e_player_position_temporal_poisition = first_or_second_to_play(p_players_num_lock, (*p_last_position_in_file));
             if (FIRST_PLAYER_E == e_player_position_temporal_poisition)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] I am first thread\n", GetCurrentThreadId());
                 // Send my guess to other player
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Sending my guess\n", GetCurrentThreadId());
                 e_status = send_message_using_file(p_players_num_lock, input_msg_params.four_digits_number, MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS + 1, p_last_position_in_file);
                 CHECK_AND_BREAK(e_status);
                 SetEvent(g_second_event);
                 // long wait - depends on other client reaction time
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Waiting for second thread\n", GetCurrentThreadId());
                 DWORD wait_stat = WaitForSingleObject(g_first_event, 1 * FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Succesfully wait for other thread\n");
                 }
                 else
                 {
                     e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                 }
                 // read other thread guess
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Reading opponents guess\n", GetCurrentThreadId());
                 int msg_size = sizeof(opponent_guess);
                 e_status = read_message_using_file(p_players_num_lock, opponent_guess, &msg_size, p_last_position_in_file);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Received msg from other thread: %s\n", opponent_guess);
                 CHECK_AND_BREAK(e_status);
                 // Compute opponents score
                 count_cows_bulls(my_four_digits_number, opponent_guess, other_player_bulls_cows);
                 // read my score
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Reading my score\n", GetCurrentThreadId());
                 msg_size = sizeof(result);
                 e_status = read_message_using_file(p_players_num_lock, result, &msg_size, p_last_position_in_file);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Received msg from other thread: %s\n", result);
                 CHECK_AND_BREAK(e_status);
                 // Send Opponents score
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Sending opponents score\n", GetCurrentThreadId());
                 e_status = send_message_using_file(p_players_num_lock, other_player_bulls_cows, sizeof(other_player_bulls_cows), p_last_position_in_file);
                 CHECK_AND_BREAK(e_status);
                 SetEvent(g_second_event);
             }
             else if(SECOND_PLAYER_E == e_player_position_temporal_poisition)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] I am second thread\n", GetCurrentThreadId());
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Waiting for first thread\n", GetCurrentThreadId());
                 DWORD wait_stat = WaitForSingleObject(g_second_event, 100 * FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Succesfully wait for other thread\n");
                 }
                 else
                 {
                     e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                 }
                 CHECK_AND_BREAK(e_status);
                 // read other thread guess
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Reading opponents guess\n", GetCurrentThreadId());
                 int msg_size = sizeof(opponent_guess);
                 e_status = read_message_using_file(p_players_num_lock, opponent_guess, &msg_size, p_last_position_in_file);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Received msg from other thread: %s\n", opponent_guess);
                 CHECK_AND_BREAK(e_status);
                 // Send my guess to other player
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Sending my guess\n", GetCurrentThreadId());
                 msg_size = sizeof(opponent_guess);
                 e_status = send_message_using_file(p_players_num_lock, input_msg_params.four_digits_number, strlen(input_msg_params.four_digits_number), p_last_position_in_file);
                 CHECK_AND_BREAK(e_status);
                 // Compute opponents score
                 count_cows_bulls(my_four_digits_number, opponent_guess, other_player_bulls_cows);
                 // Send Opponents score
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Sending opponents score\n", GetCurrentThreadId());
                 e_status = send_message_using_file(p_players_num_lock, other_player_bulls_cows, sizeof(other_player_bulls_cows), p_last_position_in_file);
                 CHECK_AND_BREAK(e_status);
                 SetEvent(g_first_event);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Waiting for first thread\n", GetCurrentThreadId());
                 wait_stat = WaitForSingleObject(g_second_event, FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Succesfully wait for other thread\n");
                 }
                 else
                 {
                     e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                 }
                 // read my score
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Reading my score\n", GetCurrentThreadId());
                 msg_size = sizeof(result);
                 e_status = read_message_using_file(p_players_num_lock, result, &msg_size, p_last_position_in_file);
                 DEBUG_PRINT(DEBUG_LEVEL_TWO, "Received msg from other thread: %s\n", result);
                 CHECK_AND_BREAK(e_status);
             }
             else
             {
                 print_error_msg("first_or_second_to_play returned INVALID PLAYER\n");
                 e_status = ERROR_FATAL_ERROR_E;
             }
             CHECK_AND_BREAK(e_status);
             if (result[NUMBER_OF_BULLS_IN_RESULT] == '4' && other_player_bulls_cows[NUMBER_OF_BULLS_IN_RESULT] == '4')
             {
                 e_game_state = GAME_STATE_DRAW_E;
             }
             else if (result[NUMBER_OF_BULLS_IN_RESULT] == '4' || other_player_bulls_cows[NUMBER_OF_BULLS_IN_RESULT] == '4')
             {
                 if (result[NUMBER_OF_BULLS_IN_RESULT] == '4')  // I win , print my name and other player number (my guess)
                 {
                     // Send my guess to other player
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Sending my number\n", GetCurrentThreadId());
                     int msg_size = sizeof(my_four_digits_number);
                     e_status = send_message_using_file(p_players_num_lock, my_four_digits_number, msg_size, p_last_position_in_file);
                     CHECK_AND_BREAK(e_status);
                     SetEvent(g_second_event);
                     out_msg_parameters[SERVER_WIN_USERNAME_PARAM_ARG_INDEX] = g_players_names[(*p_my_index)]; // Need to same my name somewhere
                     out_msg_parameters[SERVER_WIN_OPPONENT_NUMBER_PARAM_ARG_INDEX] = input_msg_params.four_digits_number;
                 }
                 else  // Other player won,  print his name and my player number (his correct guess)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Waiting for winner to reveal his number\n", GetCurrentThreadId());
                     int wait_stat = WaitForSingleObject(g_second_event, FIFTEEN_SECONDS_IN_MILLISECONDS);
                     if(wait_stat == WAIT_OBJECT_0)
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "[Thread%d] Succesfully wait for other thread\n",  GetCurrentThreadId());
                     }
                     else
                     {
                         e_status = ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E;
                     }
                     int msg_size = sizeof(opponent_guess);
                     e_status = read_message_using_file(p_players_num_lock, opponent_guess, &msg_size, p_last_position_in_file);
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Winnder number is: %s\n", opponent_guess);
                     CHECK_AND_BREAK(e_status);
                     out_msg_parameters[SERVER_WIN_USERNAME_PARAM_ARG_INDEX] = g_players_names[(*p_opponent_index)];
                     out_msg_parameters[SERVER_WIN_OPPONENT_NUMBER_PARAM_ARG_INDEX] = opponent_guess;
                 }
                 e_game_state = GAME_STATE_PLAYER_WON_E;
             }
             else
             {
                 e_game_state = GAME_STATE_ANOTHER_MOVE_E;
             }
             if (e_game_state == GAME_STATE_ANOTHER_MOVE_E)
             {
                 p_output_msg_buffer[0] = '\0';
                 char bulls_result[2] = { result[NUMBER_OF_BULLS_IN_RESULT] ,'\0' };
                 char cows_result[2] = { result[NUMBER_OF_COWS_IN_RESULT], '\0' };
                 out_msg_parameters[SERVER_GAME_RESULTS_BULLS_PARAM_ARG_INDEX] = bulls_result;
                 out_msg_parameters[SERVER_GAME_RESULTS_COWS_PARAM_ARG_INDEX] = cows_result;
                 out_msg_parameters[SERVER_GAME_RESULTS_USERNAME_PARAM_ARG_INDEX] = g_players_names[(*p_opponent_index)];
                 out_msg_parameters[SERVER_GAME_RESULTS_OPPONENT_GUESS_PARAM_ARG_INDEX] = opponent_guess;
                 e_status = send_msg(SERVER_GAME_RESULTS, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = send_msg(SERVER_PLAYER_MOVE_REQUEST, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
             }
             else if (e_game_state == GAME_STATE_PLAYER_WON_E)
             {
                 e_status = send_msg(SERVER_WIN, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = send_msg(SERVER_MAIN_MENU, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
             }
             else if (e_game_state == GAME_STATE_DRAW_E)
             {
                 e_status = send_msg(SERVER_DRAW, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
                 e_status = send_msg(SERVER_MAIN_MENU, out_msg_parameters, connection_socket);
                 CHECK_AND_BREAK(e_status);
             }
             else
             {
                 print_error_msg("FATAL ERROR! Program should not reach this point\n");
                 e_status = ERROR_FATAL_ERROR_E;
             }
             break;
         case CLIENT_DISCONNECT:
             // Check if we got here legally
             printf("Client got disconnected\n");
             e_status = send_socket_shutdown(connection_socket);
             CHECK_AND_BREAK(e_status);
             // e_status = LOCK_write_lock(p_players_num_lock);
             // CHECK_AND_BREAK(e_status);
             // if (*p_num_of_players_approved < MAX_ALLOWED_PLAYERS)
             // {
             //     (*p_num_of_players_approved)--;
             // }
             // e_status = LOCK_write_release(p_players_num_lock);
             // CHECK_AND_BREAK(e_status);
             e_status = ERROR_CLIENT_DISCONNECTED_E;
             break;
         default:
             print_error_msg("FATAL ERROR! Program should not reach this point\n");
             break;
         }
         CHECK_AND_BREAK(e_status);
     } while (FALSE);
     // Cleaup!!!
     // Was any memory allocated in this thread context?
     // Any handles that need to be closed?
     if(e_status != ERROR_OK)
     {
         if(e_status == ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E)
         {
             e_status = send_msg(SERVER_NO_OPPONENTS, out_msg_parameters, connection_socket);
             e_status = send_msg(SERVER_MAIN_MENU, out_msg_parameters, connection_socket);
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, CLIENT_DISCONNECT, CLIENT_PLAYER_MOVE, CLIENT_REQUEST, CLIENT_SETUP, CLIENT_VERSUS, count_cows_bulls(), create_comm_file(), DEBUG_LEVEL_FIVE, DEBUG_LEVEL_FOUR, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, msg_parameters_s::e_msg_type, ERROR_CLIENT_DISCONNECTED_E, ERROR_DENIED_CLIENT_E, ERROR_FATAL_ERROR_E, ERROR_OK, ERROR_TIMEOUT_WAITING_FOR_OTHER_THREAD_E, FIFTEEN_SECONDS_IN_MILLISECONDS, first_or_second_to_play(), FIRST_PLAYER_E, msg_parameters_s::four_digits_number, g_first_event, g_players_names, g_second_event, GAME_STATE_ANOTHER_MOVE_E, GAME_STATE_DRAW_E, GAME_STATE_INVALID_STATE_E, GAME_STATE_PLAYER_WON_E, get_disconnection_status_read_and_clear(), get_first_free_player_position(), get_msg_string(), get_number_of_connected_players(), increase_connected_players_by_one(), INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, INVALID_PLAYER_E, is_file_exists(), MAX_MSG_SIZE, MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS, MAX_NUMBER_OF_PARAMETERS_IN_MSG, MAX_PLAYERS, my_name_is_unique(), NUMBER_OF_BULLS_IN_RESULT, NUMBER_OF_COWS_IN_RESULT, print_error_msg, read_message_using_file(), SECOND_PLAYER_E, send_message_using_file, send_msg(), send_socket_shutdown(), SERVER_APPROVE, SERVER_APPROVED, SERVER_DENIED, SERVER_DO_NOT_APPROVE, SERVER_DRAW, SERVER_GAME_RESULTS, SERVER_GAME_RESULTS_BULLS_PARAM_ARG_INDEX, SERVER_GAME_RESULTS_COWS_PARAM_ARG_INDEX, SERVER_GAME_RESULTS_OPPONENT_GUESS_PARAM_ARG_INDEX, SERVER_GAME_RESULTS_USERNAME_PARAM_ARG_INDEX, SERVER_INVITE, SERVER_MAIN_MENU, SERVER_NO_OPPONENTS, SERVER_OPPONENT_QUIT, SERVER_PLAYER_MOVE_REQUEST, SERVER_SETUP_REQUEST, SERVER_WIN, SERVER_WIN_OPPONENT_NUMBER_PARAM_ARG_INDEX, SERVER_WIN_USERNAME_PARAM_ARG_INDEX, set_opponent_index(), set_output_msg_parameters_to_null, set_player_data(), and msg_parameters_s::username.
Referenced by server_client_comm_thread().
clear_player_data()
static error_e clear_player_data (lock_t * p_lock, const player_position_e e_player_index) static
Definition at line 1048 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         /* Lock the global database */
         e_status = LOCK_write_lock(p_lock);
         CHECK_AND_BREAK(e_status);
         /* Update database */
         // Set the player index as valid
         int current_status = g_players_playing[e_player_index];
         if(current_status == TRUE)
         {
             DEBUG_PRINT(DEBUG_LEVEL_FOUR, "The player is set to valid, clearing it.\n");
             g_players_playing[e_player_index] = FALSE;
         }
         else
         {
             print_error_msg("Trying to clear an already cleared player.\n");
         }
         // Clear name string
         for (size_t i = 0; i < USERNAME_MAX_LEGNTH_STRING; i++)
         {
             g_players_names[e_player_index][i] = '\0';
         }
         /* Release the global database */
         e_status = LOCK_write_release(p_lock);
         CHECK_AND_BREAK(e_status);
         // We validate the copy only after releasing the lock! to avoid dead locks
         if(current_status == FALSE)
         {
             e_status = ERROR_TRYING_TO_FREE_AN_INVALID_PLYAER_E;
         }
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, ERROR_TRYING_TO_FREE_AN_INVALID_PLYAER_E, g_players_names, g_players_playing, LOCK_write_lock, LOCK_write_release, print_error_msg, and USERNAME_MAX_LEGNTH_STRING.
Referenced by server_client_comm_thread().
close_signaled_threads()
static error_e close_signaled_threads (HANDLE a_thread_handles[(3)]) static
Parameters
a_thread_handles
Returns
error_e
Definition at line 917 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     for(int idx = 0; idx < NUM_OF_WORKER_THREADS; idx++)
     {
         if(NULL != a_thread_handles[idx])
         {
             DWORD wait_stat = WaitForSingleObject(a_thread_handles[idx], IGNORE);
             if(wait_stat == WAIT_OBJECT_0)
             {
                 int close_handle_stat = CloseHandle(a_thread_handles[idx]);
                 if(close_handle_stat == 0)
                 {
                     print_error_msg("Failed to close handle! GetLastError = %d\n", GetLastError());
                     e_status = ERROR_FATAL_ERROR_E;
                 }
                 else
                 {
                     a_thread_handles[idx] = NULL;
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Closed a thread!\n");
                 }
             }
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FATAL_ERROR_E, ERROR_OK, NUM_OF_WORKER_THREADS, and print_error_msg.
Referenced by main().
decrease_connected_players_by_one()
static error_e decrease_connected_players_by_one (lock_t * p_lock) static
Definition at line 1211 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     e_status = LOCK_write_lock(p_lock);
     CHECK_AND_RETURN(e_status);
     const int temp_num = g_number_of_connected_players--;
     e_status = LOCK_write_release(p_lock);
     CHECK_AND_RETURN(e_status);
     if((temp_num < 0) || (temp_num > 2))
     {
         print_error_msg("Number of connected player is: %d\n", g_number_of_connected_players);
         e_status = ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E;
     }
     DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Number of connected players: %d\n", temp_num);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_RETURN, DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E, ERROR_OK, g_number_of_connected_players, LOCK_write_lock, LOCK_write_release, and print_error_msg.
Referenced by server_client_comm_thread().
exit_thread()
static DWORD exit_thread (void * unused_param) static
Waits for user input, if input string is "exit", gracefully disconnects the clients and shuts down the server.
Parameters
[in] p_params
Returns
DWORD
Definition at line 958 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     const char exit_string[] = "exit";
     char user_input[sizeof(exit_string)] = {'\0'};
     do
     {
         char line[MAX_ERROR_STRING_LENGTH];
         if (fgets(line, sizeof(line), stdin)) {
             if (1 == sscanf_s(line, "%4c", user_input, 4))
             {
                 int strcmp_status = strcmp(user_input, exit_string);
                 if (strcmp_status == 0)
                 {
                     // Somehow need to exit :)
                     printf("I will try to close all other threads and their resources\n");
                     if (g_exit_event)
                     {
                         SetEvent(g_exit_event);
                     }
                     break;
                 }
             }
         }
         printf("Invalid input! To close the server program please enter 'exit'\n");
     } while (TRUE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, g_exit_event, and MAX_ERROR_STRING_LENGTH.
Referenced by main().
find_first_unused_thread_slot()
static int find_first_unused_thread_slot (const HANDLE a_thread_handles[(3)]) static
Parameters
a_thread_handles
Returns
int
Definition at line 890 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     int thread_idx = NUM_OF_WORKER_THREADS;
     for(int idx = 0; idx < NUM_OF_WORKER_THREADS; idx++)
     {
         if(NULL == a_thread_handles[idx])
         {
             thread_idx = idx;
             break;
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return thread_idx;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, and NUM_OF_WORKER_THREADS.
Referenced by main().
get_disconnection_status_read_and_clear()
static int get_disconnection_status_read_and_clear (lock_t * p_lock) static
Definition at line 1306 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = LOCK_write_lock(p_lock);
     int temp_disconnection_status = g_is_player_got_disconnect;
     if(temp_disconnection_status == TRUE)
     {
         g_is_player_got_disconnect = FALSE;
     }
     e_status = LOCK_write_release(p_lock);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return temp_disconnection_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, g_is_player_got_disconnect, LOCK_write_lock, and LOCK_write_release.
Referenced by act_to_msg().
get_first_free_player_position()
static player_position_e get_first_free_player_position (lock_t * p_lock, player_position_e * p_avl_positon) static
Definition at line 1098 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     player_position_e e_available_position = INVALID_PLAYER_E;
     error_e e_status = ERROR_OK;
     do
     {
         /* Input Check */
         if(NULL == p_avl_positon)
         {
             print_error_msg("Null Pointer!\n");
             e_status = ERROR_NULL_POINTER_E;
         }
         CHECK_AND_BREAK(e_status);
         /* Lock the global database */
         e_status = LOCK_write_lock(p_lock);
         CHECK_AND_BREAK(e_status);
         for (size_t i = 0; i < MAX_PLAYERS; i++)
         {
             if(g_players_playing[i] == FALSE)
             {
                 e_available_position = (player_position_e)i;
                 break;
             }
         }
         /* Release the global database */
         e_status = LOCK_write_release(p_lock);
         CHECK_AND_BREAK(e_status);
     } while (FALSE);
     // We validate the copy only after releasing the lock! to avoid dead locks
     if(e_status == ERROR_OK)
     {
         (*p_avl_positon) = e_available_position;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_NULL_POINTER_E, ERROR_OK, g_players_playing, INVALID_PLAYER_E, LOCK_write_lock, LOCK_write_release, MAX_PLAYERS, and print_error_msg.
Referenced by act_to_msg().
get_number_of_connected_players()
static int get_number_of_connected_players (lock_t * p_lock) static
Definition at line 1241 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = LOCK_write_lock(p_lock);
     const int temp_num = g_number_of_connected_players;
     e_status = LOCK_write_release(p_lock);
     if((temp_num < 0) || (temp_num > 2))
     {
         print_error_msg("Number of connected player is: %d\n", g_number_of_connected_players);
         e_status = ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E;
     }
     DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Number of connected players: %d\n", temp_num);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return temp_num;
 }
References DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E, g_number_of_connected_players, LOCK_write_lock, LOCK_write_release, and print_error_msg.
Referenced by act_to_msg().
increase_connected_players_by_one()
static error_e increase_connected_players_by_one (lock_t * p_lock) static
Definition at line 1181 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     e_status = LOCK_write_lock(p_lock);
     CHECK_AND_RETURN(e_status);
     const int temp_num = g_number_of_connected_players++;
     e_status = LOCK_write_release(p_lock);
     CHECK_AND_RETURN(e_status);
     if((temp_num < 0) || (temp_num > 2))
     {
         print_error_msg("Number of connected player is: %d\n", g_number_of_connected_players);
         e_status = ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E;
     }
     DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Number of connected players: %d\n", temp_num);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_RETURN, DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E, ERROR_OK, g_number_of_connected_players, LOCK_write_lock, LOCK_write_release, and print_error_msg.
Referenced by act_to_msg().
main()
int main (int argc, char * argv[])
Parameters
argc
argv
Returns
int
Definition at line 39 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     server_command_line_parms_t command_line_params;
     HANDLE ThreadHandles[NUM_OF_WORKER_THREADS] = { NULL, NULL, NULL };
     client_handler_params_t ThreadInputs[NUM_OF_WORKER_THREADS] = {0};
     lock_t* p_players_num_lock = LOCK_initialize_lock();
     SOCKET MainSocket = INVALID_SOCKET;
     unsigned long Address = 0;
     SOCKADDR_IN service = { 0 };
     int bindRes;
     int ListenRes;
     // Initialize Winsock.
     WSADATA wsaData;
     int StartupRes = WSAStartup( MAKEWORD( 2, 2 ), &wsaData );
     g_exit_event = CreateEventA(
     0,
     TRUE,
     FALSE,
     "__hw4_server_exit_event__"
     );
     g_first_event = CreateEventA(
     0,
     FALSE,
     FALSE,
     "__hw4_server_first_player_event__"
     );
     g_second_event = CreateEventA(
     0,
     FALSE,
     FALSE,
     "__hw4_server_second_player_event__"
     );
     HANDLE exit_thread_handle = CreateThread(
                                 NULL,
                                 0,
                                 ( LPTHREAD_START_ROUTINE ) exit_thread,
                                 NULL, // Not parameters needed
                                 0,
                                 NULL
                                 );
     if (is_file_exists(p_players_num_lock) == TRUE)
     {
         if (remove(INTER_THREAD_COMMUNICATION_FILE_NAME_STRING) == 0)
         {
             DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Deleted %s successfully\n", INTER_THREAD_COMMUNICATION_FILE_NAME_STRING);
         }
         else
         {
             print_error_msg("Failed to delete file\n")
         }
     }
     do
     {
         if ( StartupRes != ERROR_OK )
         {
             print_error_msg( "error %ld at WSAStartup( ), ending program.\n", WSAGetLastError() );
             // Tell the user that we could not find a usable WinSock DLL.
             break;
         }
         e_status = parse_command_line_input(argc, argv, &command_line_params);
         CHECK_AND_BREAK(e_status);
         // Establish connection
         // Create a socket.
         MainSocket = socket( AF_INET, SOCK_STREAM, IPPROTO_TCP );
         if ( MainSocket == INVALID_SOCKET )
         {
             print_error_msg( "Error at socket( ): %ld\n", WSAGetLastError( ) );
             break;
         }
         InetPton(AF_INET, SERVER_ADDRESS_STR_WIDE, &Address);
         if ( Address == INADDR_NONE )
         {
             print_error_msg("The string \"%s\" cannot be converted into an ip address. ending program.\n",
                     SERVER_ADDRESS_STR );
             break;
         }
         service.sin_family = AF_INET;
         service.sin_addr.s_addr = Address;
         service.sin_port = htons((unsigned short)command_line_params.port_num); //The htons function converts a u_short from host to TCP/IP network byte order
         bindRes = bind( MainSocket, ( SOCKADDR* ) &service, sizeof( service ) );
         if ( bindRes == SOCKET_ERROR )
         {
             print_error_msg( "bind( ) failed with error %ld. Ending program\n", WSAGetLastError( ) );
             break;
         }
         // Listen on the Socket.
         ListenRes = listen( MainSocket, SOMAXCONN );
         if ( ListenRes == SOCKET_ERROR )
         {
             print_error_msg( "Failed listening on socket, error %ld.\n", WSAGetLastError() );
             break;
         }
         struct timeval timeout = {1, 0};
         fd_set fds = { 0 };
         printf( "Waiting for a client to connect...\n" );
         while(TRUE)
         {
             FD_ZERO(&fds);
             FD_SET(MainSocket, &fds);
             select(MainSocket+1, &fds, NULL, NULL, &timeout);
             int is_there_a_connection_waiting = FD_ISSET(MainSocket, &fds);
             if (is_there_a_connection_waiting)
             {
                 SOCKET AcceptSocket = accept( MainSocket, NULL, NULL );
                 if ( AcceptSocket == INVALID_SOCKET )
                 {
                     print_error_msg( "Accepting connection with client failed, error %ld\n", WSAGetLastError() ) ;
                     break;
                 }
                 printf( "Client Connected.\n" );
                 e_status = close_signaled_threads(ThreadHandles);
                 CHECK_AND_BREAK(e_status);
                 const int thread_idx = find_first_unused_thread_slot(ThreadHandles);
                 if ( thread_idx == NUM_OF_WORKER_THREADS ) //no slot is available
                 {
                     printf( "No slots available for client, dropping the connection.\n" );
                     closesocket( AcceptSocket ); //Closing the socket, dropping the connection.
                 }
                 else
                 {
                     ThreadInputs[thread_idx].comm_socket               = AcceptSocket; // shallow copy: don't close
                     ThreadInputs[thread_idx].p_players_num_lock         = p_players_num_lock; // shallow copy: don't close
                     ThreadHandles[thread_idx] = CreateThread(
                         NULL,
                         0,
                         ( LPTHREAD_START_ROUTINE ) server_client_comm_thread,
                         &( ThreadInputs[thread_idx] ),
                         0,
                         NULL
                     );
                 }
             }
             else
             {
                 e_status = close_signaled_threads(ThreadHandles);
                 CHECK_AND_BREAK(e_status);
                 // Check if we need to close the server due to server operator exit request
                 if (g_exit_event)
                 {
                     DWORD wait_stat = WaitForSingleObject(g_exit_event, IGNORE);
                     if(wait_stat == WAIT_OBJECT_0)
                     {
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "NEED TO CLOSE THREAD :)\n");
                         int close_handle_stat = CloseHandle(g_exit_event);
                         if(close_handle_stat == 0)
{
                             print_error_msg("Failed to close handle! GetLastError = %d\n", GetLastError());
                             e_status = ERROR_FATAL_ERROR_E;
                         }
                         else
{
                             g_exit_event = NULL;
                             DEBUG_PRINT(DEBUG_LEVEL_TWO, "Closed a event!\n");
                             break;
                         }
                     }
                 }
             }
         }
         CHECK_AND_BREAK(e_status);
         for(int thread_idx = 0; thread_idx < NUM_OF_WORKER_THREADS; thread_idx++)
         {
             if(ThreadHandles[thread_idx])
             {
                 DWORD wait_stat = WaitForSingleObject(ThreadHandles[thread_idx], FIFTEEN_SECONDS_IN_MILLISECONDS);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "NEED TO CLOSE THREAD :)\n");
                     int close_handle_stat = CloseHandle(ThreadHandles[thread_idx]);
                     if(close_handle_stat == 0)
                     {
                         print_error_msg("Failed to close handle! GetLastError = %d\n", GetLastError());
                         e_status = ERROR_FATAL_ERROR_E;
                     }
                     else
                     {
                         ThreadHandles[thread_idx] = NULL;
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Closed thread!\n");
                         break;
                     }
                 }
                 else
                 {
                     TerminateThread(ThreadHandles[thread_idx], 0);
                 }
             }
         }
     } while (FALSE);
     closesocket(MainSocket);
     WSACleanup();
     e_status = LOCK_destroy_lock(&p_players_num_lock);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, close_signaled_threads(), client_handler_params_s::comm_socket, DEBUG_LEVEL_FIVE, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FATAL_ERROR_E, ERROR_OK, exit_thread(), FIFTEEN_SECONDS_IN_MILLISECONDS, find_first_unused_thread_slot(), g_exit_event, g_first_event, g_second_event, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, is_file_exists(), LOCK_destroy_lock(), LOCK_initialize_lock(), NUM_OF_WORKER_THREADS, client_handler_params_s::p_players_num_lock, parse_command_line_input, server_command_line_parms_s::port_num, print_error_msg, SERVER_ADDRESS_STR, SERVER_ADDRESS_STR_WIDE, and server_client_comm_thread().
my_name_is_unique()
static int my_name_is_unique (lock_t * p_lock, const char my_username[]) static
Definition at line 1267 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     int is_unique = TRUE;
     error_e e_status = LOCK_write_lock(p_lock);
     for (size_t i = 0; i < MAX_PLAYERS; i++)
     {
         if(g_players_playing[i] == TRUE)
         {
             int strcmp_status = strcmp(my_username, g_players_names[i]);
             if (strcmp_status == 0)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Sadly the name: %s is already taken.\n", my_username);
                 is_unique = FALSE;
                 break;
             }
         }
     }
     e_status = LOCK_write_release(p_lock);
     if(e_status != ERROR_OK)
     {
         print_error_msg("Issue with locks!\n");
         is_unique = -1;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return is_unique;
 }
References DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, g_players_names, g_players_playing, LOCK_write_lock, LOCK_write_release, MAX_PLAYERS, and print_error_msg.
Referenced by act_to_msg().
server_client_comm_thread()
static DWORD server_client_comm_thread (client_handler_params_t * p_params) static
Parameters
[in] p_params
Returns
DWORD
Definition at line 283 of file server.c.
 {
     error_e e_status = ERROR_OK;
     msg_parameters_t received_msg_params = {0};
     char* out_msg_params[MAX_NUMBER_OF_PARAMETERS_IN_MSG] = {NULL, NULL, NULL, NULL};
     SOCKET comm_socket = INVALID_SOCKET;
     lock_t* p_players_num_lock = NULL;
     HANDLE g_exit_event = NULL;
     do
     {
         // CHECK INPUTS!!!
         if(NULL == p_params)
         {
             print_error_msg("Thread recevied a NULL pointer for a parameter!\n");
             e_status = ERROR_NULL_POINTER_E;
         }
         else
         {
             comm_socket               = p_params->comm_socket;
             p_players_num_lock        = p_params->p_players_num_lock;
         }
         CHECK_AND_BREAK(e_status);
         // Recv and Send commands
         while (TRUE)
         {
             e_status = receive_msg(comm_socket, &received_msg_params);
             CHECK_AND_BREAK(e_status);
             e_status = act_to_msg(comm_socket,                         // SOCKET connection_socket,
                                   received_msg_params,                 // msg_parameters_t input_msg_params,
                                   p_players_num_lock,                  // lock_t* p_players_num_lock,
                                   &(p_params->last_position_in_file),  // int *p_last_position_in_file,
                                   p_params->my_four_digits_number,     // char my_four_digits_number[MAX_NUMBER_OF_DIGITS_IN_PLAYER_GUESS],
                                   &(p_params->created_comm_file),      // int *p_created_comm_file,
                                   &(p_params->my_index),               // player_position_e *p_my_index,
                                   &(p_params->opponent_index)          // player_position_e *p_opponent_index)
                                   );
             CHECK_AND_BREAK(e_status);
             // Check if we need to close the server due to server operator exit request
             if (g_exit_event)
             {
                 DWORD wait_stat = WaitForSingleObject(g_exit_event, IGNORE);
                 if(wait_stat == WAIT_OBJECT_0)
                 {
                     // TODO: Disconnect gracfully from clients
                     DEBUG_PRINT(DEBUG_LEVEL_TWO, "NEED TO CLOSE THREAD :)\n");
                     int close_handle_stat = CloseHandle(g_exit_event);
                     if(close_handle_stat == 0)
                     {
                         print_error_msg("Failed to close handle! GetLastError = %d\n", GetLastError());
                         e_status = ERROR_FATAL_ERROR_E;
                     }
                     else
                     {
                         g_exit_event = NULL;
                         DEBUG_PRINT(DEBUG_LEVEL_TWO, "Closed a event!\n");
                         break;
                     }
                 }
             }
         }
     } while (FALSE);
     DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Going to close this thread\n");
     if(ERROR_CLIENT_DISCONNECTED_UNEXPECTEDLY_E == e_status)
     {
         e_status = set_disconnection_status(p_players_num_lock);
     }
     // Cleanup
     if(p_params)
     {
         if((e_status != ERROR_CLIENT_DISCONNECTED_E) && (e_status != ERROR_DENIED_CLIENT_E))
         {
             int close_socket_status = closesocket(comm_socket);
             if(close_socket_status)
             {
                 print_error_msg("Failed to close socket with error %d (search for WSA error - WSAGetLastError)\n", WSAGetLastError());
             }
         }
         if(e_status != ERROR_DENIED_CLIENT_E)
         {
             e_status = decrease_connected_players_by_one(p_params->p_players_num_lock);
             e_status = clear_player_data(p_params->p_players_num_lock, p_params->my_index);
         }
         p_params->last_position_in_file = 0;
         if(p_params->created_comm_file == TRUE)
         {
             if (remove(INTER_THREAD_COMMUNICATION_FILE_NAME_STRING) == 0)
             {
                 DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Deleted %s successfully\n", INTER_THREAD_COMMUNICATION_FILE_NAME_STRING);
             }
             else
             {
                 print_error_msg("Failed to delete file\n")
             }
         }
     }
     return e_status;
 }
References act_to_msg(), CHECK_AND_BREAK, clear_player_data(), client_handler_params_s::comm_socket, client_handler_params_s::created_comm_file, DEBUG_LEVEL_FIVE, DEBUG_LEVEL_TWO, DEBUG_PRINT, decrease_connected_players_by_one(), ERROR_CLIENT_DISCONNECTED_E, ERROR_CLIENT_DISCONNECTED_UNEXPECTEDLY_E, ERROR_DENIED_CLIENT_E, ERROR_FATAL_ERROR_E, ERROR_NULL_POINTER_E, ERROR_OK, g_exit_event, INTER_THREAD_COMMUNICATION_FILE_NAME_STRING, client_handler_params_s::last_position_in_file, MAX_NUMBER_OF_PARAMETERS_IN_MSG, client_handler_params_s::my_four_digits_number, client_handler_params_s::my_index, client_handler_params_s::opponent_index, client_handler_params_s::p_players_num_lock, print_error_msg, receive_msg(), and set_disconnection_status().
Referenced by main().
set_disconnection_status()
static error_e set_disconnection_status (lock_t * p_lock) static
Definition at line 1329 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = LOCK_write_lock(p_lock);
     g_is_player_got_disconnect = TRUE;
     e_status = LOCK_write_release(p_lock);
     if(e_status != ERROR_OK)
     {
         print_error_msg("Issue with locks!\n");
         g_is_player_got_disconnect = -1;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_OK, g_is_player_got_disconnect, LOCK_write_lock, LOCK_write_release, and print_error_msg.
Referenced by server_client_comm_thread().
set_opponent_index()
static error_e set_opponent_index (const player_position_e e_my_idx, player_position_e * p_opponent_index) static
Definition at line 1147 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     if(NULL == p_opponent_index)
     {
         print_error_msg("NULL pointer\n");
         return ERROR_NULL_POINTER_E;
     }
     if (e_my_idx == FIRST_PLAYER_E)
     {
         (*p_opponent_index) = SECOND_PLAYER_E;
     }
     else if (e_my_idx == SECOND_PLAYER_E)
     {
         (*p_opponent_index) = FIRST_PLAYER_E;
     }
     else
     {
         (*p_opponent_index) = INVALID_PLAYER_E;
         e_status = ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E;
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_INVALID_NUMBER_OF_CONNECTED_PLAYERS_E, ERROR_NULL_POINTER_E, ERROR_OK, FIRST_PLAYER_E, INVALID_PLAYER_E, print_error_msg, and SECOND_PLAYER_E.
Referenced by act_to_msg().
set_player_data()
static error_e set_player_data (lock_t * p_lock, const player_position_e e_player_index, const char player_name[]) static
Definition at line 997 of file server.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     do
     {
         /* Input check */
         if(NULL == player_name)
         {
             print_error_msg("Null Pointer!\n");
             e_status = ERROR_NULL_POINTER_E;
         }
         CHECK_AND_BREAK(e_status);
         /* Lock the global database */
         e_status = LOCK_write_lock(p_lock);
         CHECK_AND_BREAK(e_status);
         /* Update database */
         // Set the player index as valid
         g_players_playing[e_player_index] = TRUE;
         // Save name in the database
         int strcpy_return_value = strcpy_s(g_players_names[e_player_index], USERNAME_MAX_LEGNTH_STRING, player_name);
         /* Release the global database */
         e_status = LOCK_write_release(p_lock);
         CHECK_AND_BREAK(e_status);
         // We validate the copy only after releasing the lock! to avoid dead locks
         if(strcpy_return_value)
         {
             print_error_msg("Failed copying the player name to database\n");
             e_status = ERROR_STRCPY_FAILED_E;
         }
         else
         {
             DEBUG_PRINT(DEBUG_LEVEL_FOUR, "Succesfuly copied string - the player name to global database\n");
         }
     } while (FALSE);
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, DEBUG_LEVEL_FOUR, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_NULL_POINTER_E, ERROR_OK, ERROR_STRCPY_FAILED_E, g_players_names, g_players_playing, LOCK_write_lock, LOCK_write_release, print_error_msg, and USERNAME_MAX_LEGNTH_STRING.
Referenced by act_to_msg().
Variable Documentation
g_exit_event
HANDLE g_exit_event = NULL static
Event to signal all threads the server admistrator asked to close the server.
Definition at line 20 of file server.c.
Referenced by exit_thread(), main(), and server_client_comm_thread().
g_first_event
HANDLE g_first_event = NULL static
When signaled, means that "First" player may read/wrtie to file.
Definition at line 21 of file server.c.
Referenced by act_to_msg(), and main().
g_is_player_got_disconnect
int g_is_player_got_disconnect = FALSE static
Indicated if a player god disconnected.
Definition at line 25 of file server.c.
Referenced by get_disconnection_status_read_and_clear(), and set_disconnection_status().
g_number_of_connected_players
int g_number_of_connected_players = 0 static
Number of connected players, that means they received a SERVER_APPROVED message.
Definition at line 24 of file server.c.
Referenced by decrease_connected_players_by_one(), get_number_of_connected_players(), and increase_connected_players_by_one().
g_players_names
char g_players_names[MAX_PLAYERS][USERNAME_MAX_LEGNTH_STRING] = {'\0'} static
Definition at line 27 of file server.c.
Referenced by act_to_msg(), clear_player_data(), my_name_is_unique(), and set_player_data().
g_players_playing
int g_players_playing[MAX_PLAYERS] = {0} static
Definition at line 28 of file server.c.
Referenced by clear_player_data(), get_first_free_player_position(), my_name_is_unique(), and set_player_data().
g_second_event
HANDLE g_second_event = NULL static
When signaled, means that "Second" player may read/wrtie to file.
Definition at line 22 of file server.c.
Referenced by act_to_msg(), and main().