EX4: msg_parameters_s Struct Reference
msg_parameters_s Struct Reference
#include <read_write_msg_ext.h>
Data Fields
char username [(21)]
char four_digits_number [(4)+1]
char server_denied_reason [(260)]
int num_of_bulls
int num_of_cows
message_type_e e_msg_type
Detailed Description
Definition at line 69 of file read_write_msg_ext.h.
Field Documentation
e_msg_type
message_type_e msg_parameters_s::e_msg_type
Definition at line 76 of file read_write_msg_ext.h.
Referenced by act_to_msg(), main(), and message_read().
four_digits_number
char msg_parameters_s::four_digits_number[(4)+1]
Definition at line 72 of file read_write_msg_ext.h.
Referenced by act_to_msg(), message_read(), and print_game_result().
num_of_bulls
int msg_parameters_s::num_of_bulls
Definition at line 74 of file read_write_msg_ext.h.
Referenced by message_read(), and print_game_result().
num_of_cows
int msg_parameters_s::num_of_cows
Definition at line 75 of file read_write_msg_ext.h.
Referenced by message_read(), and print_game_result().
server_denied_reason
char msg_parameters_s::server_denied_reason[(260)]
Definition at line 73 of file read_write_msg_ext.h.
Referenced by main(), and message_read().
username
char msg_parameters_s::username[(21)]
Definition at line 71 of file read_write_msg_ext.h.
Referenced by act_to_msg(), message_read(), and print_game_result().
The documentation for this struct was generated from the following file:
read_write_msg_ext.h